// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { PageSystemFlag } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPageDeleteOutput = { deleted: boolean, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPageOutput = { id: bigint, tag: string, is_system: PageSystemFlag, title: MultiLang, content: MultiLang, cover: MultiLang, created_at: string, updated_at: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPageUpdateInput = { tag: string, title: MultiLang, content: MultiLang, cover: MultiLang, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPageUpdateOutput = { id: bigint, tag: string, is_system: PageSystemFlag, title: MultiLang, content: MultiLang, cover: MultiLang, created_at: string, updated_at: string, };

