// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { CreditTransactionType, CreditType } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminCreditAdjustInput = { username: string, credit_type: CreditType, amount: string, remark: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserCreditTransactionOutput = { id: string, user_id: string, credit_type: CreditType, amount: string, transaction_type: CreditTransactionType, related_key: string | null, remark: string | null, created_at: string, };

