// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { AdminType } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDatatableRow = { id: bigint, identity: string, username: string, email: string | null, name: string, admin_type: AdminType, abilities: string[], created_at: string, updated_at: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDatatableSummaryOutput = { total_admin_counts: bigint, total_filtered: bigint, developer_count: bigint, superadmin_count: bigint, admin_count: bigint, };

