// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntroducerChangeDatatableRow = { id: string, user_id: string, from_user_id: string | null, to_user_id: string, admin_id: string, remark: string | null, created_at: string, updated_at: string, };

