// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

export type AdminType = "developer" | "superadmin" | "admin";

export type AuthClientType = "web" | "mobile";

export type Permission = "admin.read" | "admin.manage";
