use crate::config::{ConfigsFile, Locales};
use crate::schema::{parse_attachments, to_owner_type, to_snake, to_title_case, Schema};
use std::collections::BTreeSet;
use std::error::Error;
use std::fs;

pub fn generate_localized(
    locales: &Locales,
    cfgs: &ConfigsFile,
    schema: &Schema,
    out_dir: &std::path::Path,
) -> Result<(), Box<dyn Error>> {
    let mut out = String::new();
    let has_loader_functions = schema.models.values().any(|cfg| {
        cfg.localized.is_some() || cfg.meta.is_some() || !parse_attachments(cfg).is_empty()
    });
    let needs_resize_rule = cfgs
        .attachment_types
        .values()
        .any(|attachment_type| attachment_type.resize.is_some());

    out.push_str("#![allow(dead_code, unused_imports, unused_variables, unused_mut)]\n");
    out.push_str("// AUTO-GENERATED FILE — DO NOT EDIT\n");
    out.push_str("// Generated by build.rs from schema.toml + configs.toml\n\n");

    if has_loader_functions {
        out.push_str("use anyhow::Result;\n");
        out.push_str("use std::collections::HashMap;\n");
        out.push_str("use core_db::common::sql::{generate_snowflake_i64, DbConn, Op};\n");
        out.push_str(
            "use crate::generated::models::attachment::{Attachment as AttachmentModel, AttachmentCol};\n",
        );
        out.push_str(
            "use crate::generated::models::localized::{Localized as LocalizedModel, LocalizedCol};\n",
        );
        out.push_str("use crate::generated::models::meta::{Meta as MetaModel, MetaCol};\n");
        out.push_str("use uuid::Uuid;\n\n");
    }
    if needs_resize_rule {
        out.push_str("use core_db::platform::attachments::types::{AttachmentRules, ResizeRule};\n");
    } else {
        out.push_str("use core_db::platform::attachments::types::AttachmentRules;\n");
    }

    out.push_str(&format!(
        "pub const DEFAULT_LOCALE: &str = \"{}\";\n\n",
        locales.default
    ));

    let timezone = locales.timezone.as_deref().unwrap_or("+00:00");
    out.push_str(&format!(
        "pub const DEFAULT_TIMEZONE: &str = \"{}\";\n\n",
        timezone
    ));

    out.push_str("pub const SUPPORTED_LOCALES: &[&str] = &[\n");
    for lang in &locales.supported {
        out.push_str(&format!("    \"{}\",\n", lang));
    }
    out.push_str("];\n\n");

    // Generate Locale Enum
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, ts_rs::TS)]\n");
    out.push_str("pub enum Locale {\n");
    for lang in &locales.supported {
        let variant = to_title_case(lang);
        out.push_str(&format!("    #[serde(rename = \"{}\")]\n", lang));
        out.push_str(&format!("    {},\n", variant));
    }
    out.push_str("}\n\n");

    if has_loader_functions {
        out.push_str("pub async fn upsert_localized_many<'a>(\n");
        out.push_str("    db: DbConn<'a>,\n");
        out.push_str("    owner_type: &str,\n");
        out.push_str("    owner_id: i64,\n");
        out.push_str("    field: &str,\n");
        out.push_str("    values: &HashMap<String, String>,\n");
        out.push_str(") -> Result<()> {\n");
        out.push_str("    for (locale, value) in values {\n");
        out.push_str("        let current = LocalizedModel::new(db.clone(), None)\n");
        out.push_str("            .query()\n");
        out.push_str("            .where_owner_type(Op::Eq, owner_type.to_string())\n");
        out.push_str("            .where_owner_id(Op::Eq, owner_id)\n");
        out.push_str("            .where_field(Op::Eq, field.to_string())\n");
        out.push_str("            .where_locale(Op::Eq, locale.clone())\n");
        out.push_str("            .first()\n");
        out.push_str("            .await?;\n");
        out.push_str("        if let Some(current) = current {\n");
        out.push_str("            LocalizedModel::new(db.clone(), None)\n");
        out.push_str("                .update()\n");
        out.push_str("                .where_id(Op::Eq, current.id)\n");
        out.push_str("                .set_value(value.clone())\n");
        out.push_str("                .save()\n");
        out.push_str("                .await?;\n");
        out.push_str("        } else {\n");
        out.push_str("            LocalizedModel::new(db.clone(), None)\n");
        out.push_str("                .insert()\n");
        out.push_str("                .set_id(generate_snowflake_i64())\n");
        out.push_str("                .set_owner_type(owner_type.to_string())\n");
        out.push_str("                .set_owner_id(owner_id)\n");
        out.push_str("                .set_field(field.to_string())\n");
        out.push_str("                .set_locale(locale.clone())\n");
        out.push_str("                .set_value(value.clone())\n");
        out.push_str("                .save()\n");
        out.push_str("                .await?;\n");
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("    Ok(())\n");
        out.push_str("}\n\n");

        out.push_str("pub async fn load_owner_localized<'a>(\n");
        out.push_str("    db: DbConn<'a>,\n");
        out.push_str("    owner_type: &str,\n");
        out.push_str("    ids: &[i64],\n");
        out.push_str("    fields: &[&str],\n");
        out.push_str(") -> Result<core_db::platform::localized::types::LocalizedMap> {\n");
        out.push_str("    if ids.is_empty() || fields.is_empty() {\n");
        out.push_str(
            "        return Ok(core_db::platform::localized::types::LocalizedMap::default());\n",
        );
        out.push_str("    }\n");
        out.push_str("    let owner_ids: Vec<i64> = ids.to_vec();\n");
        out.push_str(
            "    let field_names: Vec<String> = fields.iter().map(|field| (*field).to_string()).collect();\n",
        );
        out.push_str("    let rows = LocalizedModel::new(db, None)\n");
        out.push_str("        .query()\n");
        out.push_str("        .where_owner_type(Op::Eq, owner_type.to_string())\n");
        out.push_str("        .where_in(LocalizedCol::OwnerId, &owner_ids)\n");
        out.push_str("        .where_in(LocalizedCol::Field, &field_names)\n");
        out.push_str("        .get()\n");
        out.push_str("        .await?;\n");
        out.push_str(
            "    let mut out: HashMap<String, HashMap<i64, HashMap<String, String>>> = HashMap::new();\n",
        );
        out.push_str("    for row in rows {\n");
        out.push_str("        out.entry(row.field.clone())\n");
        out.push_str("            .or_default()\n");
        out.push_str("            .entry(row.owner_id)\n");
        out.push_str("            .or_default()\n");
        out.push_str("            .insert(row.locale.clone(), row.value.clone());\n");
        out.push_str("    }\n");
        out.push_str("    Ok(core_db::platform::localized::types::LocalizedMap::new(out))\n");
        out.push_str("}\n\n");

        out.push_str("pub async fn upsert_meta_many<'a>(\n");
        out.push_str("    db: DbConn<'a>,\n");
        out.push_str("    owner_type: &str,\n");
        out.push_str("    owner_id: i64,\n");
        out.push_str("    values: &HashMap<String, serde_json::Value>,\n");
        out.push_str(") -> Result<()> {\n");
        out.push_str("    for (field, value) in values {\n");
        out.push_str("        let current = MetaModel::new(db.clone(), None)\n");
        out.push_str("            .query()\n");
        out.push_str("            .where_owner_type(Op::Eq, owner_type.to_string())\n");
        out.push_str("            .where_owner_id(Op::Eq, owner_id)\n");
        out.push_str("            .where_field(Op::Eq, field.clone())\n");
        out.push_str("            .first()\n");
        out.push_str("            .await?;\n");
        out.push_str("        if let Some(current) = current {\n");
        out.push_str("            MetaModel::new(db.clone(), None)\n");
        out.push_str("                .update()\n");
        out.push_str("                .where_id(Op::Eq, current.id)\n");
        out.push_str("                .set_value(value.clone())\n");
        out.push_str("                .save()\n");
        out.push_str("                .await?;\n");
        out.push_str("        } else {\n");
        out.push_str("            MetaModel::new(db.clone(), None)\n");
        out.push_str("                .insert()\n");
        out.push_str("                .set_id(generate_snowflake_i64())\n");
        out.push_str("                .set_owner_type(owner_type.to_string())\n");
        out.push_str("                .set_owner_id(owner_id)\n");
        out.push_str("                .set_field(field.clone())\n");
        out.push_str("                .set_value(value.clone())\n");
        out.push_str("                .save()\n");
        out.push_str("                .await?;\n");
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("    Ok(())\n");
        out.push_str("}\n\n");

        out.push_str("pub async fn load_owner_meta<'a>(\n");
        out.push_str("    db: DbConn<'a>,\n");
        out.push_str("    owner_type: &str,\n");
        out.push_str("    ids: &[i64],\n");
        out.push_str("    fields: &[&str],\n");
        out.push_str(") -> Result<core_db::platform::meta::types::MetaMap> {\n");
        out.push_str("    if ids.is_empty() || fields.is_empty() {\n");
        out.push_str("        return Ok(core_db::platform::meta::types::MetaMap::default());\n");
        out.push_str("    }\n");
        out.push_str("    let owner_ids: Vec<i64> = ids.to_vec();\n");
        out.push_str(
            "    let field_names: Vec<String> = fields.iter().map(|field| (*field).to_string()).collect();\n",
        );
        out.push_str("    let rows = MetaModel::new(db, None)\n");
        out.push_str("        .query()\n");
        out.push_str("        .where_owner_type(Op::Eq, owner_type.to_string())\n");
        out.push_str("        .where_in(MetaCol::OwnerId, &owner_ids)\n");
        out.push_str("        .where_in(MetaCol::Field, &field_names)\n");
        out.push_str("        .get()\n");
        out.push_str("        .await?;\n");
        out.push_str(
            "    let mut out: HashMap<String, HashMap<i64, serde_json::Value>> = HashMap::new();\n",
        );
        out.push_str("    for row in rows {\n");
        out.push_str("        out.entry(row.field.clone())\n");
        out.push_str("            .or_default()\n");
        out.push_str("            .insert(row.owner_id, row.value.clone());\n");
        out.push_str("    }\n");
        out.push_str("    Ok(core_db::platform::meta::types::MetaMap::new(out))\n");
        out.push_str("}\n\n");

        out.push_str("pub async fn clear_attachment_field<'a>(\n");
        out.push_str("    db: DbConn<'a>,\n");
        out.push_str("    owner_type: &str,\n");
        out.push_str("    owner_id: i64,\n");
        out.push_str("    field: &str,\n");
        out.push_str(") -> Result<()> {\n");
        out.push_str("    let rows = AttachmentModel::new(db.clone(), None)\n");
        out.push_str("        .query()\n");
        out.push_str("        .where_owner_type(Op::Eq, owner_type.to_string())\n");
        out.push_str("        .where_owner_id(Op::Eq, owner_id)\n");
        out.push_str("        .where_field(Op::Eq, field.to_string())\n");
        out.push_str("        .get()\n");
        out.push_str("        .await?;\n");
        out.push_str("    for row in rows {\n");
        out.push_str("        AttachmentModel::new(db.clone(), None)\n");
        out.push_str("            .query()\n");
        out.push_str("            .where_id(Op::Eq, row.id)\n");
        out.push_str("            .delete()\n");
        out.push_str("            .await?;\n");
        out.push_str("    }\n");
        out.push_str("    Ok(())\n");
        out.push_str("}\n\n");

        out.push_str("pub async fn add_attachments<'a>(\n");
        out.push_str("    db: DbConn<'a>,\n");
        out.push_str("    owner_type: &str,\n");
        out.push_str("    owner_id: i64,\n");
        out.push_str("    field: &str,\n");
        out.push_str("    values: &[core_db::platform::attachments::types::AttachmentInput],\n");
        out.push_str(") -> Result<()> {\n");
        out.push_str("    for value in values {\n");
        out.push_str("        let now = time::OffsetDateTime::now_utc();\n");
        out.push_str("        let attachment_id = value.id.unwrap_or_else(Uuid::new_v4);\n");
        out.push_str("        AttachmentModel::new(db.clone(), None)\n");
        out.push_str("            .insert()\n");
        out.push_str("            .set_id(attachment_id)\n");
        out.push_str("            .set_owner_type(owner_type.to_string())\n");
        out.push_str("            .set_owner_id(owner_id)\n");
        out.push_str("            .set_field(field.to_string())\n");
        out.push_str("            .set_path(value.path.clone())\n");
        out.push_str("            .set_content_type(value.content_type.clone())\n");
        out.push_str("            .set_size(value.size)\n");
        out.push_str("            .set_width(value.width)\n");
        out.push_str("            .set_height(value.height)\n");
        out.push_str("            .set_created_at(now)\n");
        out.push_str("            .set_updated_at(now)\n");
        out.push_str("            .save()\n");
        out.push_str("            .await?;\n");
        out.push_str("    }\n");
        out.push_str("    Ok(())\n");
        out.push_str("}\n\n");

        out.push_str("pub async fn replace_single_attachment<'a>(\n");
        out.push_str("    db: DbConn<'a>,\n");
        out.push_str("    owner_type: &str,\n");
        out.push_str("    owner_id: i64,\n");
        out.push_str("    field: &str,\n");
        out.push_str("    value: &core_db::platform::attachments::types::AttachmentInput,\n");
        out.push_str(") -> Result<()> {\n");
        out.push_str(
            "    clear_attachment_field(db.clone(), owner_type, owner_id, field).await?;\n",
        );
        out.push_str("    add_attachments(db, owner_type, owner_id, field, std::slice::from_ref(value)).await\n");
        out.push_str("}\n\n");

        out.push_str("pub async fn delete_attachment_ids<'a>(\n");
        out.push_str("    db: DbConn<'a>,\n");
        out.push_str("    owner_type: &str,\n");
        out.push_str("    owner_id: i64,\n");
        out.push_str("    field: &str,\n");
        out.push_str("    ids: &[Uuid],\n");
        out.push_str(") -> Result<()> {\n");
        out.push_str("    for id in ids {\n");
        out.push_str("        AttachmentModel::new(db.clone(), None)\n");
        out.push_str("            .query()\n");
        out.push_str("            .where_id(Op::Eq, *id)\n");
        out.push_str("            .where_owner_type(Op::Eq, owner_type.to_string())\n");
        out.push_str("            .where_owner_id(Op::Eq, owner_id)\n");
        out.push_str("            .where_field(Op::Eq, field.to_string())\n");
        out.push_str("            .delete()\n");
        out.push_str("            .await?;\n");
        out.push_str("    }\n");
        out.push_str("    Ok(())\n");
        out.push_str("}\n\n");

        out.push_str("pub async fn load_owner_attachments<'a>(\n");
        out.push_str("    db: DbConn<'a>,\n");
        out.push_str("    owner_type: &str,\n");
        out.push_str("    ids: &[i64],\n");
        out.push_str("    fields: &[&str],\n");
        out.push_str(") -> Result<core_db::platform::attachments::types::AttachmentMap> {\n");
        out.push_str("    if ids.is_empty() || fields.is_empty() {\n");
        out.push_str(
            "        return Ok(core_db::platform::attachments::types::AttachmentMap::default());\n",
        );
        out.push_str("    }\n");
        out.push_str("    let owner_ids: Vec<i64> = ids.to_vec();\n");
        out.push_str(
            "    let field_names: Vec<String> = fields.iter().map(|field| (*field).to_string()).collect();\n",
        );
        out.push_str("    let rows = AttachmentModel::new(db, None)\n");
        out.push_str("        .query()\n");
        out.push_str("        .where_owner_type(Op::Eq, owner_type.to_string())\n");
        out.push_str("        .where_in(AttachmentCol::OwnerId, &owner_ids)\n");
        out.push_str("        .where_in(AttachmentCol::Field, &field_names)\n");
        out.push_str("        .get()\n");
        out.push_str("        .await?;\n");
        out.push_str("    let mut out: HashMap<String, HashMap<i64, Vec<core_db::platform::attachments::types::Attachment>>> = HashMap::new();\n");
        out.push_str("    for row in rows {\n");
        out.push_str("        out.entry(row.field.clone())\n");
        out.push_str("            .or_default()\n");
        out.push_str("            .entry(row.owner_id)\n");
        out.push_str("            .or_default()\n");
        out.push_str("            .push(core_db::platform::attachments::types::Attachment {\n");
        out.push_str("                id: row.id,\n");
        out.push_str("                path: row.path.clone(),\n");
        out.push_str("                url: core_db::platform::attachments::types::attachment_url(&row.path, None),\n");
        out.push_str("                content_type: row.content_type,\n");
        out.push_str("                size: row.size,\n");
        out.push_str("                width: row.width,\n");
        out.push_str("                height: row.height,\n");
        out.push_str("                created_at: row.created_at,\n");
        out.push_str("            });\n");
        out.push_str("    }\n");
        out.push_str("    Ok(core_db::platform::attachments::types::AttachmentMap::new(out))\n");
        out.push_str("}\n\n");
    }

    out.push_str("impl Locale {\n");
    out.push_str("    pub fn as_str(&self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for lang in &locales.supported {
        let variant = to_title_case(lang);
        out.push_str(&format!(
            "            Locale::{} => \"{}\",\n",
            variant, lang
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("impl From<Locale> for String {\n");
    out.push_str("    fn from(l: Locale) -> Self {\n");
    out.push_str("        l.as_str().to_string()\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("impl std::fmt::Display for Locale {\n");
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("        write!(f, \"{}\", self.as_str())\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    let mut owner_consts: BTreeSet<String> = BTreeSet::new();

    out.push_str(
        "#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]\n",
    );
    out.push_str("pub struct LocalizedText {\n");
    for lang in &locales.supported {
        out.push_str(&format!("    pub {}: String,\n", lang));
    }
    out.push_str("}\n\n");

    out.push_str("impl LocalizedText {\n");
    out.push_str("    pub fn get(&self, locale: &str) -> &str {\n");
    out.push_str("        match locale {\n");
    for lang in &locales.supported {
        out.push_str(&format!("            \"{}\" => &self.{},\n", lang, lang));
    }
    out.push_str(&format!("            _ => &self.{},\n", locales.default));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    pub fn to_map(&self) -> std::collections::BTreeMap<String, String> {\n");
    out.push_str("        let mut out = std::collections::BTreeMap::new();\n");
    for lang in &locales.supported {
        out.push_str(&format!(
            "        out.insert(\"{lang}\".to_string(), self.{lang}.clone());\n"
        ));
    }
    out.push_str("        out\n");
    out.push_str("    }\n");
    out.push_str(
        "    pub fn from_map(map: &std::collections::BTreeMap<String, String>) -> Self {\n",
    );
    out.push_str("        Self {\n");
    for lang in &locales.supported {
        out.push_str(&format!(
            "            {lang}: map.get(\"{lang}\").cloned().unwrap_or_default(),\n"
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl ts_rs::TS for LocalizedText {\n");
    out.push_str("    type WithoutGenerics = Self;\n");
    out.push_str("    fn name() -> String { \"LocalizedText\".to_string() }\n");
    out.push_str("    fn inline() -> String { Self::name() }\n");
    out.push_str(
        "    fn inline_flattened() -> String { panic!(\"LocalizedText cannot be flattened\") }\n",
    );
    out.push_str("    fn decl() -> String { panic!(\"LocalizedText declaration is provided by shared platform types\") }\n");
    out.push_str("    fn decl_concrete() -> String { Self::decl() }\n");
    out.push_str("}\n\n");
    out.push_str("pub trait LocalizedMapHelper {\n");
    out.push_str(
        "    fn get_localized_text(&self, field: &str, owner_id: i64) -> Option<LocalizedText>;\n",
    );
    out.push_str("}\n\n");

    out.push_str(
        "impl LocalizedMapHelper for core_db::platform::localized::types::LocalizedMap {\n",
    );
    out.push_str(
        "    fn get_localized_text(&self, field: &str, owner_id: i64) -> Option<LocalizedText> {\n",
    );
    out.push_str("        let by_owner = self.inner.get(field)?;\n");
    out.push_str("        let by_locale = by_owner.get(&owner_id)?;\n");
    out.push_str("        if by_locale.is_empty() { return None; }\n");
    out.push_str("        let mut out = LocalizedText {\n");
    for lang in &locales.supported {
        out.push_str(&format!("            {}: String::new(),\n", lang));
    }
    out.push_str("        };\n");
    out.push_str("        for &loc in SUPPORTED_LOCALES {\n");
    out.push_str("            if let Some(v) = by_locale.get(loc) {\n");
    out.push_str("                match loc {\n");
    for lang in &locales.supported {
        out.push_str(&format!(
            "                    \"{}\" => out.{} = v.clone(),\n",
            lang, lang
        ));
    }
    out.push_str("                    _ => {}\n");
    out.push_str("                }\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("        if let Some(default_val) = by_locale.get(DEFAULT_LOCALE) {\n");
    for lang in &locales.supported {
        out.push_str(&format!(
            "            if out.{}.is_empty() {{ out.{} = default_val.clone(); }}\n",
            lang, lang
        ));
    }
    out.push_str("        }\n");
    out.push_str("        Some(out)\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    for (name, cfg) in &schema.models {
        let Some(localized_fields) = &cfg.localized else {
            continue;
        };
        let model_snake = to_snake(name);
        let model_title = to_title_case(&model_snake);
        let model_const = model_snake.to_uppercase();
        let owner_type = to_owner_type(name);

        if owner_consts.insert(model_const.clone()) {
            out.push_str(&format!(
                "pub const {model_const}_OWNER_TYPE: &str = \"{owner_type}\";\n"
            ));
        }
        out.push_str(&format!("pub const {model_const}_FIELDS: &[&str] = &[\n"));
        for field in localized_fields {
            out.push_str(&format!("    \"{}\",\n", field));
        }
        out.push_str("];\n\n");

        out.push_str(&format!(
            "pub async fn load_{model_snake}_localized<'a>(db: DbConn<'a>, ids: &[i64]) -> Result<core_db::platform::localized::types::LocalizedMap> {{\n"
        ));
        out.push_str(&format!(
            "    load_owner_localized(db, {model_const}_OWNER_TYPE, ids, {model_const}_FIELDS).await\n"
        ));
        out.push_str("}\n\n");

        let trait_name = format!("{}Localized", model_title);
        out.push_str(&format!("pub trait {} {{\n", trait_name));
        for field in localized_fields {
            let field_snake = to_snake(field);
            out.push_str(&format!(
                "    fn {model_snake}_{field_snake}_translations(&self, id: i64) -> Option<crate::generated::LocalizedText>;\n"
            ));
            out.push_str(&format!(
                "    fn {model_snake}_{field_snake}(&self, id: i64) -> Option<String>;\n"
            ));
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "impl {} for core_db::platform::localized::types::LocalizedMap {{\n",
            trait_name
        ));
        for field in localized_fields {
            let field_snake = to_snake(field);
            out.push_str(&format!(
                "    fn {model_snake}_{field_snake}_translations(&self, id: i64) -> Option<crate::generated::LocalizedText> {{\n"
            ));
            out.push_str(&format!(
                "        self.get_localized_text(\"{}\", id)\n",
                field
            ));
            out.push_str("    }\n");

            out.push_str(&format!(
                "    fn {model_snake}_{field_snake}(&self, id: i64) -> Option<String> {{\n"
            ));
            out.push_str("        let locale = core_i18n::current_locale();\n");
            out.push_str(&format!(
                "        self.get_value(\"{}\", id, locale)\n",
                field
            ));
            out.push_str("    }\n");
        }
        out.push_str("}\n\n");
    }

    // Attachment type rules from configs.toml
    out.push_str("pub fn get_attachment_rules(name: &str) -> Option<AttachmentRules> {\n");
    out.push_str("    match name {\n");
    for (name, t) in &cfgs.attachment_types {
        out.push_str(&format!(
            "        \"{n}\" => Some(AttachmentRules {{\n",
            n = name
        ));
        out.push_str("            allowed: vec![\n");
        for a in &t.allowed {
            out.push_str(&format!("                \"{}\".to_string(),\n", a));
        }
        out.push_str("            ],\n");
        if let Some(r) = &t.resize {
            out.push_str("            resize: Some(ResizeRule {\n");
            if let Some(w) = r.width {
                out.push_str(&format!("                width: Some({}),\n", w));
            } else {
                out.push_str("                width: None,\n");
            }
            if let Some(h) = r.height {
                out.push_str(&format!("                height: Some({}),\n", h));
            } else {
                out.push_str("                height: None,\n");
            }
            if let Some(q) = r.quality {
                out.push_str(&format!("                quality: Some({}),\n", q));
            } else {
                out.push_str("                quality: None,\n");
            }
            out.push_str("            }),\n");
        } else {
            out.push_str("            resize: None,\n");
        }
        out.push_str("        }),\n");
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Meta helpers/constants
    for (name, cfg) in &schema.models {
        let Some(meta_fields) = &cfg.meta else {
            continue;
        };
        let model_snake = to_snake(name);
        let model_const = model_snake.to_uppercase();
        let owner_type = to_owner_type(name);

        if cfg.localized.is_none() && owner_consts.insert(model_const.clone()) {
            out.push_str(&format!(
                "pub const {model_const}_OWNER_TYPE: &str = \"{owner_type}\";\n"
            ));
        }
        out.push_str(&format!(
            "pub const {model_const}_META_FIELDS: &[&str] = &[\n"
        ));
        for field in meta_fields {
            let mut parts = field.splitn(2, ':');
            let fname = parts.next().unwrap_or("");
            out.push_str(&format!("    \"{}\",\n", fname));
        }
        out.push_str("];\n\n");

        out.push_str(&format!(
            "pub async fn load_{model_snake}_meta<'a>(db: DbConn<'a>, ids: &[i64]) -> Result<core_db::platform::meta::types::MetaMap> {{\n"
        ));
        out.push_str(&format!(
            "    load_owner_meta(db, {model_const}_OWNER_TYPE, ids, {model_const}_META_FIELDS).await\n"
        ));
        out.push_str("}\n\n");
    }

    // Attachment helpers/constants
    for (name, cfg) in &schema.models {
        let attachment_fields = parse_attachments(cfg);
        if attachment_fields.is_empty() {
            continue;
        }
        let model_snake = to_snake(name);
        let model_const = model_snake.to_uppercase();
        let owner_type = to_owner_type(name);
        if cfg.localized.is_none() && cfg.meta.is_none() && owner_consts.insert(model_const.clone())
        {
            out.push_str(&format!(
                "pub const {model_const}_OWNER_TYPE: &str = \"{owner_type}\";\n"
            ));
        }
        out.push_str(&format!(
            "pub const {model_const}_ATTACHMENT_FIELDS: &[&str] = &[\n"
        ));
        for field in &attachment_fields {
            out.push_str(&format!("    \"{}\",\n", field.name));
        }
        out.push_str("];\n\n");
        out.push_str(&format!(
            "pub async fn load_{model_snake}_attachments<'a>(db: DbConn<'a>, ids: &[i64]) -> Result<core_db::platform::attachments::types::AttachmentMap> {{\n"
        ));
        out.push_str(&format!(
            "    load_owner_attachments(db, {model_const}_OWNER_TYPE, ids, {model_const}_ATTACHMENT_FIELDS).await\n"
        ));
        out.push_str("}\n\n");
    }

    fs::write(out_dir.join("localized.rs"), out)?;
    Ok(())
}
