use std::collections::HashMap;

use axum::extract::{FromRequest, Multipart, Request};
use core_i18n::t;
use serde_json::Value;
use validator::Validate;

use crate::error::AppError;
use crate::extract::json_cleaner::clean_json_strings;
use crate::extract::validation::{transform_validation_errors, AsyncValidate};

use super::file_upload::FileUpload;
use super::validated_json::GetDb;

/// Trait generated by the `#[rustforge_contract]` macro for structs
/// that have `#[rf(attachment(...))]` fields.
pub trait MultipartContract: Sized {
    /// Returns `(field_name, attachment_type_name)` for each file field.
    fn file_fields() -> &'static [(&'static str, &'static str)];

    /// Construct the struct from the JSON portion + extracted files.
    fn from_multipart_parts(
        json: Value,
        files: HashMap<String, FileUpload>,
    ) -> Result<Self, String>;
}

/// Multipart extractor with sync validation (like `ContractJson` but for multipart).
pub struct ContractMultipart<T>(pub T);

impl<T, S> FromRequest<S> for ContractMultipart<T>
where
    T: serde::de::DeserializeOwned + Validate + MultipartContract + Send + Sync + 'static,
    S: Send + Sync,
{
    type Rejection = AppError;

    async fn from_request(req: Request, state: &S) -> Result<Self, Self::Rejection> {
        let multipart = Multipart::from_request(req, state)
            .await
            .map_err(|e| AppError::BadRequest(format!("{}: {}", t("Invalid multipart"), e)))?;

        let data = parse_multipart_into::<T>(multipart).await?;

        if let Err(e) = data.validate() {
            return Err(AppError::Validation {
                message: t("Validation failed"),
                errors: transform_validation_errors(e),
            });
        }

        Ok(ContractMultipart(data))
    }
}

impl<T> aide::OperationInput for ContractMultipart<T>
where
    T: schemars::JsonSchema,
{
    fn operation_input(
        ctx: &mut aide::generate::GenContext,
        operation: &mut aide::openapi::Operation,
    ) {
        crate::extract::validation::apply_json_request_body_schema::<T>(ctx, operation);
    }
}

/// Multipart extractor with sync + async validation (like `AsyncContractJson` but for multipart).
pub struct AsyncContractMultipart<T>(pub T);

impl<T, S> FromRequest<S> for AsyncContractMultipart<T>
where
    T: serde::de::DeserializeOwned
        + Validate
        + MultipartContract
        + AsyncValidate
        + Send
        + Sync
        + 'static,
    S: Send + Sync + GetDb,
{
    type Rejection = AppError;

    async fn from_request(req: Request, state: &S) -> Result<Self, Self::Rejection> {
        let multipart = Multipart::from_request(req, state)
            .await
            .map_err(|e| AppError::BadRequest(format!("{}: {}", t("Invalid multipart"), e)))?;

        let data = parse_multipart_into::<T>(multipart).await?;

        if let Err(e) = data.validate() {
            return Err(AppError::Validation {
                message: t("Validation failed"),
                errors: transform_validation_errors(e),
            });
        }

        if let Err(e) = data.validate_async(state.db()).await {
            return Err(AppError::Validation {
                message: t("Validation failed"),
                errors: transform_validation_errors(e),
            });
        }

        Ok(AsyncContractMultipart(data))
    }
}

impl<T> aide::OperationInput for AsyncContractMultipart<T>
where
    T: schemars::JsonSchema,
{
    fn operation_input(
        ctx: &mut aide::generate::GenContext,
        operation: &mut aide::openapi::Operation,
    ) {
        crate::extract::validation::apply_json_request_body_schema::<T>(ctx, operation);
    }
}

/// Parse a multipart request into struct `T` via `MultipartContract`.
async fn parse_multipart_into<T>(mut multipart: Multipart) -> Result<T, AppError>
where
    T: serde::de::DeserializeOwned + MultipartContract,
{
    let file_field_names: HashMap<&str, &str> = T::file_fields().iter().copied().collect();
    let mut json_map = serde_json::Map::new();
    let mut files: HashMap<String, FileUpload> = HashMap::new();

    while let Some(field) = multipart.next_field().await.map_err(AppError::from)? {
        let field_name = field
            .name()
            .map(str::to_string)
            .ok_or_else(|| AppError::BadRequest(t("Invalid multipart field")))?;

        if file_field_names.contains_key(field_name.as_str()) {
            // File field
            if field.file_name().is_some() {
                let filename = field.file_name().map(ToString::to_string);
                let content_type = field
                    .content_type()
                    .map(ToString::to_string)
                    .unwrap_or_else(|| "application/octet-stream".to_string());
                let bytes = field.bytes().await.map_err(AppError::from)?;
                if !bytes.is_empty() {
                    let size = bytes.len();
                    files.insert(
                        field_name,
                        FileUpload {
                            filename,
                            content_type,
                            size,
                            bytes,
                        },
                    );
                }
            }
        } else {
            // Text field → JSON map
            let text = field.text().await.map_err(AppError::from)?;
            json_map.insert(field_name, Value::String(text));
        }
    }

    let mut json_value = Value::Object(json_map);
    clean_json_strings(&mut json_value);

    T::from_multipart_parts(json_value, files)
        .map_err(|e| AppError::BadRequest(format!("{}: {}", t("Invalid input"), e)))
}
