// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by build.rs from schema.toml + configs.toml
#![allow(dead_code, unused_imports, unused_variables, unused_mut)]
{{imports}}
{{constants}}
{{row_view_json_section}}{{column_model_section}}{{query_section}}{{insert_section}}{{update_section}}{{datatable_section}}{{active_record_section}}
