// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CryptoNetworkOption = { id: string, name: string, symbol: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserWithdrawalHistoryQuery = { limit: bigint | null, cursor: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserWithdrawalHistoryResponse = { items: Array<UserWithdrawalOutput>, next_cursor: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserWithdrawalInput = { crypto_network_id: bigint, crypto_wallet_address: string, amount: string, password: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserWithdrawalOutput = { id: string, status: string, crypto_network_name: string, crypto_wallet_address: string, amount: string, fee: string, net_amount: string, created_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WalletLedgerEntry = { id: string, transaction_type: string, amount: string, related_key: string | null, created_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WalletLedgerQuery = { limit: bigint | null, cursor: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WalletLedgerResponse = { items: Array<WalletLedgerEntry>, next_cursor: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WithdrawalConfigResponse = { networks: Array<CryptoNetworkOption>, fee_percentage: string, min_amount: string, };
