#![allow(dead_code, unused_imports, unused_variables, unused_mut)]
// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by build.rs from schema.toml + configs.toml

{{imports}}
pub const DEFAULT_LOCALE: &str = "{{default_locale}}";

pub const DEFAULT_TIMEZONE: &str = "{{default_timezone}}";

pub const SUPPORTED_LOCALES: &[&str] = &[
{{supported_locales}}
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, ts_rs::TS)]
pub enum Locale {
{{locale_variants}}
}

{{loader_functions_section}}{{locale_impls_section}}{{localized_text_section}}{{localized_input_section}}{{model_localized_section}}{{attachment_rules_section}}{{meta_helpers_section}}{{attachment_helpers_section}}
