// Auto-generated by db-gen. Do not edit.

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema)]
pub struct PermissionMeta {
    pub key: &'static str,
    pub guard: &'static str,
    pub label: &'static str,
    pub group: &'static str,
    pub description: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
pub enum Permission {
    #[serde(rename = "article.read")]
    ArticleRead,
    #[serde(rename = "article.manage")]
    ArticleManage,
}

impl ts_rs::TS for Permission {
    type WithoutGenerics = Self;

    fn name() -> String { "Permission".to_string() }
    fn inline() -> String { Self::name() }
    fn inline_flattened() -> String { panic!("Permission cannot be flattened") }
    fn decl() -> String { "type Permission = \"article.read\" | \"article.manage\";".to_string() }
    fn decl_concrete() -> String { Self::decl() }
}

pub const PERMISSION_META: &[PermissionMeta] = &[
    PermissionMeta { key: "article.read", guard: "admin", label: "Read Articles", group: "article", description: "Read article records" },
    PermissionMeta { key: "article.manage", guard: "admin", label: "Manage Articles", group: "article", description: "Manage article records" },
];

impl Permission {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ArticleRead => "article.read",
            Self::ArticleManage => "article.manage",
        }
    }

    pub fn from_str(value: &str) -> Option<Self> {
        match value {
            "article.read" => Some(Self::ArticleRead),
            "article.manage" => Some(Self::ArticleManage),
            _ => None,
        }
    }

    pub const fn all() -> &'static [Self] {
        &[
            Self::ArticleRead,
            Self::ArticleManage,
        ]
    }

    pub const fn guard(self) -> &'static str {
        match self {
            Self::ArticleRead => "admin",
            Self::ArticleManage => "admin",
        }
    }

    pub const fn meta(self) -> &'static PermissionMeta {
        match self {
            Self::ArticleRead => &PERMISSION_META[0],
            Self::ArticleManage => &PERMISSION_META[1],
        }
    }

    pub fn by_guard(guard: &str) -> Vec<Self> {
        Self::all()
            .iter()
            .copied()
            .filter(|permission| permission.guard().eq_ignore_ascii_case(guard))
            .collect()
    }
}

impl std::fmt::Display for Permission {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl AsRef<str> for Permission {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
