export function Requests() {
    return (
        <div className="space-y-10">
            <div className="space-y-4">
                <h1 className="text-4xl font-extrabold text-gray-900">Requests &amp; Validation</h1>
                <p className="text-xl text-gray-500">
                    Canonical request-boundary semantics for contracts, validation, partial updates, and generated TypeScript wire shapes.
                </p>
            </div>

            <div className="prose prose-orange max-w-none">
                <p>
                    For rule-by-rule validator coverage, see <a href="#/validation-rules">Validation Rules</a>. This page focuses on boundary semantics and how request DTOs should be used inside handlers and workflows.
                </p>

                <h2>Canonical boundary</h2>
                <p>
                    Use <code>core_web::contracts</code> plus extractor types from <code>core_web::extract</code> as the only trusted HTTP input boundary. Handlers and workflows should receive already-validated DTOs instead of re-validating the same fields again.
                </p>
                <ul>
                    <li><code>ContractJson&lt;T&gt;</code>: sync JSON parse + validation boundary.</li>
                    <li><code>AsyncContractJson&lt;T&gt;</code>: sync + async DB-backed validation boundary.</li>
                    <li><code>RequestContract</code>: DTO trait surface generated by <code>#[rustforge_contract]</code>.</li>
                </ul>

                <pre className="bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto">
                    <code className="language-rust">{`use core_web::contracts::ContractJson;

async fn create(
    ContractJson(req): ContractJson<MyCreateInput>,
) -> Result<ApiResponse<MyOutput>, AppError> {
    run_workflow(req).await
}`}</code>
                </pre>

                <h2>Choose the right field shape</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Field type</th>
                            <th>Use when</th>
                            <th>Meaning</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><code>String</code></td>
                            <td>Required input</td>
                            <td>The field must be present and must contain a value that passes its rules.</td>
                        </tr>
                        <tr>
                            <td><code>Option&lt;T&gt;</code></td>
                            <td>Nullable create/full input</td>
                            <td>Missing and explicit <code>null</code> both become <code>None</code>.</td>
                        </tr>
                        <tr>
                            <td><code>Patch&lt;T&gt;</code></td>
                            <td>Partial update input</td>
                            <td>Distinguishes <code>Missing</code>, <code>Null</code>, and <code>Value(T)</code>.</td>
                        </tr>
                        <tr>
                            <td><code>Vec&lt;T&gt;</code></td>
                            <td>Ordered list input</td>
                            <td>Use when array order and length are meaningful and should not collapse to null semantics.</td>
                        </tr>
                    </tbody>
                </table>

                <h2>Blank string, null, and omitted are not the same</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Input payload</th>
                            <th><code>Option&lt;String&gt;</code></th>
                            <th><code>Patch&lt;String&gt;</code></th>
                            <th>Implication</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>field omitted</td>
                            <td><code>None</code></td>
                            <td><code>Missing</code></td>
                            <td>Only <code>Patch&lt;T&gt;</code> preserves “not sent”.</td>
                        </tr>
                        <tr>
                            <td><code>field: null</code></td>
                            <td><code>None</code></td>
                            <td><code>Null</code></td>
                            <td>Use for explicit clear semantics.</td>
                        </tr>
                        <tr>
                            <td><code>field: ""</code></td>
                            <td><code>Some(String::new())</code></td>
                            <td><code>Value(String::new())</code></td>
                            <td>Blank string is still a string; do not treat it as null by convention alone.</td>
                        </tr>
                    </tbody>
                </table>

                <h2>Pattern examples</h2>
                <pre className="bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto text-xs">
                    <code className="language-rust">{`use core_web::{contracts::rustforge_contract, Patch};

#[rustforge_contract]
pub struct CreateAdminInput {
    #[rf(length(min = 3, max = 32))]
    #[rf(alpha_dash)]
    pub username: String,

    #[serde(default)]
    #[rf(email)]
    pub email: Option<String>,
}

#[rustforge_contract]
pub struct UpdateAdminInput {
    #[serde(default)]
    #[rf(email)]
    pub email: Patch<String>,

    #[serde(default)]
    #[rf(length(min = 8, max = 128))]
    pub password: Patch<String>,
}`}</code>
                </pre>

                <h2>Path-driven async validation</h2>
                <p>
                    For update routes, path parameters remain the source of truth. Inject them into the DTO before async validation rather than duplicating ID checks in multiple layers.
                </p>
                <pre className="bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto text-xs">
                    <code className="language-rust">{`#[rustforge_contract]
pub struct UpdateAdminInput {
    #[serde(skip, default)]
    __target_id: i64,

    #[serde(default)]
    #[rf(async_unique(
        table = "admin",
        column = "username",
        ignore(column = "id", field = "__target_id")
    ))]
    pub username: Patch<String>,
}

impl UpdateAdminInput {
    pub fn with_target_id(mut self, id: i64) -> Self {
        self.__target_id = id;
        self
    }
}`}</code>
                </pre>

                <h2>Sync and async rules</h2>
                <p>
                    Keep simple DB checks declarative on the DTO via <code>#[rf(async_*)]</code>. Move complex multi-field or cross-table rules into manual <code>AsyncValidate</code> implementations.
                </p>
                <pre className="bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto text-xs">
                    <code className="language-rust">{`#[rustforge_contract]
pub struct RegisterInput {
    #[rf(length(min = 3, max = 32))]
    #[rf(alpha_dash)]
    pub username: String,

    #[rf(async_unique(table = "admin", column = "username"))]
    pub login_username: String,
}`}</code>
                </pre>

                <h2>Frontend wire-shape ownership</h2>
                <p>
                    Request/response DTOs, datatable rows, and shared platform types should stay owned by Rust. Use <code>make gen-types</code> so frontend contracts follow the Rust source of truth instead of handwritten TypeScript copies.
                </p>
                <pre className="bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto text-xs">
                    <code className="language-rust">{`#[derive(TS)]
#[ts(export, export_to = "admin/types/")]
pub struct AdminMeOutput {
    pub id: SnowflakeId,
    pub username: String,
    pub admin_type: generated::models::AdminType,
    pub scopes: Vec<String>,
}`}</code>
                </pre>

                <h2>Bootstrap runtime injection</h2>
                <p>
                    Request-driven frontend runtime state such as locale metadata and enabled countries should come from <code>/api/bootstrap.js</code>, not hardcoded frontend constants. Keep backend bootstrap generation and frontend runtime parsing in sync.
                </p>

                <h2>Keep the flow simple</h2>
                <ol>
                    <li>Define the DTO contract and rules once.</li>
                    <li>Extract via <code>ContractJson</code> or <code>AsyncContractJson</code>.</li>
                    <li>Inject path-derived state only when needed for async validation.</li>
                    <li>Hand the trusted DTO into workflow code.</li>
                    <li>Generate TS types from Rust instead of duplicating the wire shape.</li>
                </ol>
            </div>
        </div>
    )
}
