// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by build.rs from Rust model sources + configs.toml
#![allow(dead_code, unused_imports, unused_variables, unused_mut)]
use anyhow::Result;
use std::collections::HashMap;
use serde_json::Value as JsonValue;
use serde::{Deserialize, Serialize};
use schemars::JsonSchema;
use sqlx::FromRow;
use core_db::common::sql::{BindValue, Op, OrderDir, SetMode, bind, bind_query, bind_scalar, generate_snowflake_i64, is_sql_profiler_enabled, format_duration, record_profiled_query, DbConn};
use core_db::common::pagination::resolve_per_page;
use core_datatable::{AutoDataTable, BoxFuture, DataTableColumnDescriptor, DataTableContext, DataTableInput, DataTableRelationColumnDescriptor, GeneratedTableAdapter, ParsedFilter, SortDirection};
use core_db::platform::attachments::types::{Attachment, AttachmentInput, AttachmentMap};
use uuid::Uuid;
use core_db::platform::localized::types::LocalizedMap;
use crate::generated::models::common::{FieldChange, FieldInput, Page, log_observer_error, renumber_placeholders};
use core_db::common::model_api::{Column, Create, ManyRelation, ModelDef, OneRelation, Patch, Query, QueryState};
use core_db::platform::meta::types::MetaMap;
use crate::generated::localized;
use core_i18n::current_locale;
use crate::generated::models::user::{UserDbCol, UserModel, UserRow, UserRel};
use crate::generated::models::profile::{ProfileDbCol, ProfileModel, ProfileRow};
use crate::generated::localized::LocalizedMapHelper;
use super::enums::*;
use core_db::common::model_observer::{ModelEvent, try_get_observer};
const HAS_CREATED_AT: bool = false;
const HAS_UPDATED_AT: bool = false;
const HAS_SOFT_DELETE: bool = false;
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[doc(hidden)]
pub struct ArticleCreate {
    pub id: FieldInput<i64>,
    pub author_id: FieldInput<i64>,
    pub status: FieldInput<ArticleStatus>,
    pub is_system: FieldInput<ArticleSystemFlag>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[doc(hidden)]
pub struct ArticleChanges {
    pub id: Option<FieldChange<i64>>,
    pub author_id: Option<FieldChange<i64>>,
    pub status: Option<FieldChange<ArticleStatus>>,
    pub is_system: Option<FieldChange<ArticleSystemFlag>>,
}

#[derive(Debug, Clone, FromRow, Serialize, Deserialize, JsonSchema)]
#[doc(hidden)]
pub struct ArticleRow {
    pub id: i64,
    pub author_id: i64,
    pub status: ArticleStatus,
    pub is_system: ArticleSystemFlag,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct ArticleRecord {
    pub id: i64,
    pub author_id: i64,
    pub status: ArticleStatus,
    pub is_system: ArticleSystemFlag,
    pub status_explained: String,
    pub is_system_explained: String,
    pub title: Option<String>,
    pub title_translations: Option<localized::LocalizedText>,
    pub hero: Option<Attachment>,
    pub hero_url: Option<String>,
    pub meta: std::collections::HashMap<String, JsonValue>,
    pub author: Option<UserRow>,
}

impl ArticleRecord {
    pub fn update<'db>(&self, db: impl Into<DbConn<'db>>) -> Patch<'db, ArticleModel> {
        ArticleModel::query(db.into()).where_col(ArticleDbCol::Id, Op::Eq, self.id.clone()).patch()
    }
    pub fn meta_flags(&self) -> Option<bool> { self.meta.get("flags").and_then(|v| v.as_bool()) }
    pub fn meta_extra_as<T: serde::de::DeserializeOwned>(&self) -> anyhow::Result<Option<T>> { match self.meta.get("extra") { None => Ok(None), Some(v) => Ok(Some(serde_json::from_value(v.clone())?)), } }
    pub async fn upsert_title<'a>(&self, db: DbConn<'a>, input: Option<localized::LocalizedInput>) -> Result<()> {
        let Some(input) = input else { return Ok(()); };
        if input.is_empty() { return Ok(()); }
        let map = input.to_hashmap();
        localized::upsert_localized_many(db, localized::ARTICLE_OWNER_TYPE, self.id, "title", &map).await
    }
    pub async fn clear_title<'a>(&self, db: DbConn<'a>) -> Result<()> {
        localized::delete_localized_field(db, localized::ARTICLE_OWNER_TYPE, self.id, "title").await
    }
}

fn hydrate_record(row: ArticleRow, loc: &LocalizedMap, meta: &MetaMap, attachments: &AttachmentMap, base_url: Option<&str>) -> ArticleRecord {
    let locale = current_locale();
    let mut record = ArticleRecord {
        id: row.id,
        author_id: row.author_id,
        status: row.status,
        is_system: row.is_system,
        status_explained: row.status.explained_label(),
        is_system_explained: row.is_system.explained_label(),
        title: None,
        title_translations: None,
        hero: None,
        hero_url: None,
        meta: HashMap::new(),
        author: None,
    };
    let ml_title = loc.get_localized_text("title", record.id);
    if let Some(ref ml) = ml_title {
        record.title = Some(ml.get(locale).to_string());
    }
    record.title_translations = ml_title;
    record.meta = meta.get_all_for_owner(record.id);
    record.hero = attachments.get_single("hero", record.id);
    record.hero_url = record.hero.as_ref().map(|a| a.url_with_base(base_url));
    record
}

impl ArticleRecord {
    pub fn one<R>(&self, relation: R) -> Option<&R::Target>
    where
        R: core_db::common::model_api::RecordOneRelation<ArticleModel>,
    {
        R::get(relation, self)
    }
    pub fn many<R>(&self, relation: R) -> &[R::Target]
    where
        R: core_db::common::model_api::RecordManyRelation<ArticleModel>,
    {
        R::get(relation, self)
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ArticleCol;
impl ArticleCol {
    pub const ID: Column<ArticleModel, i64> = Column::new("id");
    pub const AUTHOR_ID: Column<ArticleModel, i64> = Column::new("author_id");
    pub const STATUS: Column<ArticleModel, ArticleStatus> = Column::new("status");
    pub const IS_SYSTEM: Column<ArticleModel, ArticleSystemFlag> = Column::new("is_system");
}

fn resolve_article_db_col(sql: &str) -> Option<ArticleDbCol> {
    match sql {
        "id" => Some(ArticleDbCol::Id),
        "author_id" => Some(ArticleDbCol::AuthorId),
        "status" => Some(ArticleDbCol::Status),
        "is_system" => Some(ArticleDbCol::IsSystem),
        _ => None,
    }
}

#[derive(Debug, Clone, Copy, JsonSchema)]
pub enum ArticleDbCol {
    Id,
    AuthorId,
    Status,
    IsSystem,
}

impl ArticleDbCol {
    pub const fn all() -> &'static [ArticleDbCol] {
        &[ArticleDbCol::Id, ArticleDbCol::AuthorId, ArticleDbCol::Status, ArticleDbCol::IsSystem]
    }
    pub const fn as_sql(self) -> &'static str {
        match self {
            ArticleDbCol::Id => "id",
            ArticleDbCol::AuthorId => "author_id",
            ArticleDbCol::Status => "status",
            ArticleDbCol::IsSystem => "is_system",
        }
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ArticleRel;
impl ArticleRel {
    pub const AUTHOR: OneRelation<ArticleModel, UserRow, 0> = OneRelation::<ArticleModel, UserRow, 0>::new("author");
}

async fn load_author<'db>(db: DbConn<'db>, parents: &[ArticleRow]) -> Result<HashMap<i64, Option<UserRow>>> {
        if parents.is_empty() { return Ok(HashMap::new()); }
        let mut fk_vals = Vec::new();
        let mut parent_pairs = Vec::new();
        for p in parents {
            fk_vals.push(p.author_id.clone());
            parent_pairs.push((p.id.clone(), Some(p.author_id.clone())));
        }
        if fk_vals.is_empty() { return Ok(HashMap::new()); }
        let placeholders: Vec<String> = (1..=fk_vals.len()).map(|i| format!("${}", i)).collect();
        let sql = format!("SELECT * FROM users WHERE id IN ({})", placeholders.join(", "));
        let mut q = sqlx::query_as::<_, UserRow>(&sql);
        for fk in fk_vals { q = bind(q, fk.into()); }
        let rows = db.fetch_all(q).await?;
        let mut by_pk: HashMap<i64, UserRow> = HashMap::new();
        for row in rows { by_pk.insert(row.id.clone(), row); }
        let mut out = HashMap::new();
        for (pid, fk) in parent_pairs {
            out.insert(pid, fk.and_then(|k| by_pk.get(&k).cloned()));
        }
        Ok(out)
    }

pub struct ArticleCreateInner<'db> {
    pub(crate) state: core_db::common::model_api::CreateState<'db>,
    translations: HashMap<&'static str, HashMap<String, String>>,
    meta: HashMap<String, JsonValue>,
    attachments_single: HashMap<&'static str, AttachmentInput>,
    attachments_multi: HashMap<&'static str, Vec<AttachmentInput>>,
}

impl<'db> ArticleCreateInner<'db> {
    pub fn new(db: DbConn<'db>, base_url: Option<String>) -> Self {
        Self {
            state: core_db::common::model_api::CreateState::new(db, base_url, "articles"),
            translations: HashMap::new(),
            meta: HashMap::new(),
            attachments_single: HashMap::new(),
            attachments_multi: HashMap::new(),
        }
    }


pub fn set_id(mut self, val: i64) -> Self {
        self.state = self.state.set_col("id", val.into());
        self
    }
    pub fn set_author_id(mut self, val: i64) -> Self {
        self.state = self.state.set_col("author_id", val.into());
        self
    }
    pub fn set_status(mut self, val: ArticleStatus) -> Self {
        self.state = self.state.set_col("status", val.into());
        self
    }
    pub fn set_is_system(mut self, val: ArticleSystemFlag) -> Self {
        self.state = self.state.set_col("is_system", val.into());
        self
    }
    pub fn set_title_lang(mut self, locale: localized::Locale, val: impl Into<String>) -> Self {
        self.translations.entry("title").or_default().insert(locale.into(), val.into());
        self
    }
    pub fn set_title_langs(mut self, langs: localized::LocalizedText) -> Self {
        if !langs.en.is_empty() { self = self.set_title_lang(localized::Locale::En, langs.en); }
        if !langs.zh.is_empty() { self = self.set_title_lang(localized::Locale::Zh, langs.zh); }
        self
    }
    pub fn set_title_input(mut self, input: Option<localized::LocalizedInput>) -> Self {
        let Some(input) = input else { return self; };
        if input.is_empty() { return self; }
        let map = input.to_hashmap();
        for (locale, val) in map {
            self.translations.entry("title").or_default().insert(locale, val);
        }
        self
    }
    pub fn set_meta_flags(mut self, val: bool) -> Self {
        self.meta.insert("flags".to_string(), JsonValue::Bool(val));
        self
    }
    pub fn set_meta_extra(mut self, val: JsonValue) -> Self {
        self.meta.insert("extra".to_string(), val);
        self
    }
    pub fn set_meta_extra_as<T: serde::Serialize>(mut self, val: &T) -> anyhow::Result<Self> {
        self.meta.insert("extra".to_string(), serde_json::to_value(val)?);
        Ok(self)
    }
    pub fn set_attachment_hero(mut self, att: AttachmentInput) -> Self {
        self.attachments_single.insert("hero", att);
        self
    }
    pub fn on_conflict_do_nothing(mut self, conflict_cols: &[ArticleDbCol]) -> Self {
        self.state = self.state.on_conflict_do_nothing(&conflict_cols.iter().map(|c| c.as_sql()).collect::<Vec<_>>());
        self
    }
    pub fn on_conflict_update(mut self, conflict_cols: &[ArticleDbCol]) -> Self {
        self.state = self.state.on_conflict_update(&conflict_cols.iter().map(|c| c.as_sql()).collect::<Vec<_>>());
        self
    }
    fn to_create_input(&self) -> Result<ArticleCreate> {
        let mut input = ArticleCreate::default();
        for (col_name, bind) in self.state.col_names.iter().zip(self.state.binds.iter()) {
            match *col_name {
                "id" => {
                    let value = match bind {
            BindValue::I64(value) => value.clone(),
            other => anyhow::bail!("unexpected bind value '{:?}' for type 'i64'", other),
        };
                    input.id = FieldInput::Set(value);
                }
                "author_id" => {
                    let value = match bind {
            BindValue::I64(value) => value.clone(),
            other => anyhow::bail!("unexpected bind value '{:?}' for type 'i64'", other),
        };
                    input.author_id = FieldInput::Set(value);
                }
                "status" => {
                    let value = match bind {
                BindValue::String(value) => ArticleStatus::from_storage(value)
                    .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleStatus'", value))?,
                BindValue::I64(value) => {
                    let raw = value.to_string();
                    ArticleStatus::from_storage(&raw)
                        .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleStatus'", value))?
                }
                other => anyhow::bail!("unexpected bind value '{:?}' for type 'ArticleStatus'", other),
            };
                    input.status = FieldInput::Set(value);
                }
                "is_system" => {
                    let value = match bind {
                BindValue::String(value) => ArticleSystemFlag::from_storage(value)
                    .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleSystemFlag'", value))?,
                BindValue::I64(value) => {
                    let raw = value.to_string();
                    ArticleSystemFlag::from_storage(&raw)
                        .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleSystemFlag'", value))?
                }
                other => anyhow::bail!("unexpected bind value '{:?}' for type 'ArticleSystemFlag'", other),
            };
                    input.is_system = FieldInput::Set(value);
                }
                _ => {}
            }
        }
        Ok(input)
    }


pub async fn save(self) -> Result<ArticleRecord> {
        let __create_input = if try_get_observer().is_some() {
            Some(self.to_create_input()?)
        } else {
            None
        };
        if let Some(observer) = try_get_observer() {
            if let Some(create_input) = __create_input.as_ref() {
                let event = ModelEvent { model: "article", table: "articles", record_key: None };
                let data = serde_json::to_value(create_input)?;
                observer.on_creating(&event, &data).await?;
            }
        }
        let db_conn = self.state.db.clone();
        match db_conn {
            DbConn::Pool(pool) => {
                let tx = pool.begin().await?;
                let tx_lock = std::sync::Arc::new(tokio::sync::Mutex::new(tx));
                let (record, row) = {
                    let db = DbConn::tx(tx_lock.clone());
                    self.save_with_db(db).await?
                };
                let tx = std::sync::Arc::try_unwrap(tx_lock)
                    .map_err(|_| anyhow::anyhow!("transaction scope still has active handles"))?
                    .into_inner();
                tx.commit().await?;
                if let Some(observer) = try_get_observer() {
                    let event = ModelEvent { model: "article", table: "articles", record_key: Some(format!("{}", row.id)) };
                    match serde_json::to_value(&row) {
                        Ok(data) => {
                            if let Err(err) = observer.on_created(&event, &data).await {
                                log_observer_error("created", "article", &err);
                            }
                        }
                        Err(err) => log_observer_error("created", "article", &err),
                    }
                }
                Ok(record)
            }
            DbConn::Tx(_) => {
                let (record, row) = self.save_with_db(db_conn).await?;
                if let Some(observer) = try_get_observer() {
                    let event = ModelEvent { model: "article", table: "articles", record_key: Some(format!("{}", row.id)) };
                    match serde_json::to_value(&row) {
                        Ok(data) => {
                            if let Err(err) = observer.on_created(&event, &data).await {
                                log_observer_error("created", "article", &err);
                            }
                        }
                        Err(err) => log_observer_error("created", "article", &err),
                    }
                }
                Ok(record)
            }
        }
    }

    async fn save_with_db<'tx>(mut self, db: DbConn<'tx>) -> Result<(ArticleRecord, ArticleRow)> {
        if !self.state.col_names.contains(&"id") {
            self.state = self.state.set_col("id", generate_snowflake_i64().into());
        }
        if self.state.col_names.is_empty() {
            anyhow::bail!("insert: no columns set");
        }
        let base_url = self.state.base_url.clone();
        let (sql, binds) = self.state.build_insert_sql();
        let __profiler_binds = if is_sql_profiler_enabled() { binds.iter().map(|b| format!("{}", b)).collect::<Vec<_>>().join(", ") } else { String::new() };
        let __profiler_start = std::time::Instant::now();
        let mut q = sqlx::query_as::<_, ArticleRow>(&sql);
        for b in binds {
            q = bind(q, b);
        }
        let row = db.fetch_one(q).await?;
        record_profiled_query("articles", "INSERT", &sql, &__profiler_binds, __profiler_start.elapsed());
        if !self.translations.is_empty() {
            let supported = localized::SUPPORTED_LOCALES;
            if let Some(map) = self.translations.get("title") {
                let mut filtered = HashMap::new();
                for (loc, val) in map {
                    if supported.contains(&loc.as_str()) { filtered.insert(loc.clone(), val.clone()); }
                }
                if !filtered.is_empty() {
                    localized::upsert_localized_many(db.clone(), localized::ARTICLE_OWNER_TYPE, row.id, "title", &filtered).await?;
                }
            }
        }
        if !self.meta.is_empty() {
            localized::upsert_meta_many(db.clone(), localized::ARTICLE_OWNER_TYPE, row.id, &self.meta).await?;
        }
        if !self.attachments_single.is_empty() || !self.attachments_multi.is_empty() {
            for (field, att) in &self.attachments_single {
                localized::replace_single_attachment(db.clone(), localized::ARTICLE_OWNER_TYPE, row.id, field, att).await?;
            }
            for (field, list) in &self.attachments_multi {
                localized::add_attachments(db.clone(), localized::ARTICLE_OWNER_TYPE, row.id, field, list).await?;
            }
        }
        let localized = localized::load_article_localized(db, &[row.id]).await?;
        let attachments = localized::load_article_attachments(db, &[row.id]).await?;
        let meta_map = localized::load_article_meta(db, &[row.id]).await?;
        let record = hydrate_record(row.clone(), &localized, &meta_map, &attachments, base_url.as_deref());
        Ok((record, row))
    }
}

pub struct ArticlePatchInner<'db> {
    pub(crate) state: core_db::common::model_api::PatchState<'db>,
    translations: HashMap<&'static str, HashMap<String, String>>,
    meta: HashMap<String, JsonValue>,
    attachments_single: HashMap<&'static str, AttachmentInput>,
    attachments_multi: HashMap<&'static str, Vec<AttachmentInput>>,
    attachments_clear_single: Vec<&'static str>,
    attachments_delete_multi: HashMap<&'static str, Vec<Uuid>>,
}

impl<'db> ArticlePatchInner<'db> {
    pub fn new(db: DbConn<'db>, base_url: Option<String>) -> Self {
        Self {
            state: core_db::common::model_api::PatchState::new(db, base_url, "articles"),
            translations: HashMap::new(),
            meta: HashMap::new(),
            attachments_single: HashMap::new(),
            attachments_multi: HashMap::new(),
            attachments_clear_single: Vec::new(),
            attachments_delete_multi: HashMap::new(),
        }
    }


pub fn set_id(mut self, val: i64) -> Self {
        self.state = self.state.assign_col(ArticleDbCol::Id.as_sql(), val.into());
        self
    }
    pub fn increment_id(mut self, val: i64) -> Self {
        self.state = self.state.increment_col(ArticleDbCol::Id.as_sql(), val.into());
        self
    }
    pub fn decrement_id(mut self, val: i64) -> Self {
        self.state = self.state.decrement_col(ArticleDbCol::Id.as_sql(), val.into());
        self
    }
    pub fn set_author_id(mut self, val: i64) -> Self {
        self.state = self.state.assign_col(ArticleDbCol::AuthorId.as_sql(), val.into());
        self
    }
    pub fn increment_author_id(mut self, val: i64) -> Self {
        self.state = self.state.increment_col(ArticleDbCol::AuthorId.as_sql(), val.into());
        self
    }
    pub fn decrement_author_id(mut self, val: i64) -> Self {
        self.state = self.state.decrement_col(ArticleDbCol::AuthorId.as_sql(), val.into());
        self
    }
    pub fn set_status(mut self, val: ArticleStatus) -> Self {
        self.state = self.state.assign_col(ArticleDbCol::Status.as_sql(), val.into());
        self
    }
    pub fn set_is_system(mut self, val: ArticleSystemFlag) -> Self {
        self.state = self.state.assign_col(ArticleDbCol::IsSystem.as_sql(), val.into());
        self
    }
    pub fn set_title_lang(mut self, locale: localized::Locale, val: impl Into<String>) -> Self {
        self.translations.entry("title").or_default().insert(locale.into(), val.into());
        self
    }
    pub fn set_title_langs(mut self, langs: localized::LocalizedText) -> Self {
        if !langs.en.is_empty() { self = self.set_title_lang(localized::Locale::En, langs.en); }
        if !langs.zh.is_empty() { self = self.set_title_lang(localized::Locale::Zh, langs.zh); }
        self
    }
    pub fn set_title_input(mut self, input: Option<localized::LocalizedInput>) -> Self {
        let Some(input) = input else { return self; };
        if input.is_empty() { return self; }
        let map = input.to_hashmap();
        for (locale, val) in map {
            self.translations.entry("title").or_default().insert(locale, val);
        }
        self
    }
    pub fn set_meta_flags(mut self, val: bool) -> Self {
        self.meta.insert("flags".to_string(), JsonValue::Bool(val));
        self
    }
    pub fn set_meta_extra(mut self, val: JsonValue) -> Self {
        self.meta.insert("extra".to_string(), val);
        self
    }
    pub fn set_meta_extra_as<T: serde::Serialize>(mut self, val: &T) -> anyhow::Result<Self> {
        self.meta.insert("extra".to_string(), serde_json::to_value(val)?);
        Ok(self)
    }
    pub fn set_attachment_hero(mut self, att: AttachmentInput) -> Self {
        self.attachments_single.insert("hero", att);
        self
    }
    pub fn clear_attachment_hero(mut self) -> Self {
        if !self.attachments_clear_single.contains(&"hero") { self.attachments_clear_single.push("hero"); }
        self
    }
    pub fn where_id(mut self, op: Op, val: i64) -> Self {
        let idx = self.state.where_binds.len() + 1;
        self.state.where_sql.push(format!("{} {} ${}", ArticleDbCol::Id.as_sql(), op.as_sql(), idx));
        self.state.where_binds.push(val.into());
        self
    }
    pub fn where_author_id(mut self, op: Op, val: i64) -> Self {
        let idx = self.state.where_binds.len() + 1;
        self.state.where_sql.push(format!("{} {} ${}", ArticleDbCol::AuthorId.as_sql(), op.as_sql(), idx));
        self.state.where_binds.push(val.into());
        self
    }
    pub fn where_status(mut self, op: Op, val: ArticleStatus) -> Self {
        let idx = self.state.where_binds.len() + 1;
        self.state.where_sql.push(format!("{} {} ${}", ArticleDbCol::Status.as_sql(), op.as_sql(), idx));
        self.state.where_binds.push(val.into());
        self
    }
    pub fn where_is_system(mut self, op: Op, val: ArticleSystemFlag) -> Self {
        let idx = self.state.where_binds.len() + 1;
        self.state.where_sql.push(format!("{} {} ${}", ArticleDbCol::IsSystem.as_sql(), op.as_sql(), idx));
        self.state.where_binds.push(val.into());
        self
    }
    pub fn where_col<T: Into<BindValue>>(mut self, col: ArticleDbCol, op: Op, val: T) -> Self {
        let idx = self.state.where_binds.len() + 1;
        self.state.where_sql.push(format!("{} {} ${}", col.as_sql(), op.as_sql(), idx));
        self.state.where_binds.push(val.into());
        self
    }
    fn where_raw<T: Into<BindValue>>(mut self, clause: impl Into<String>, binds: impl IntoIterator<Item = T>) -> Self {
        let mut clause = clause.into();
        let incoming: Vec<BindValue> = binds.into_iter().map(Into::into).collect();
        let mut idx = self.state.where_binds.len() + 1;
        while let Some(pos) = clause.find('?') {
            let ph = format!("${}", idx);
            clause.replace_range(pos..pos + 1, &ph);
            idx += 1;
        }
        self.state.where_sql.push(clause);
        self.state.where_binds.extend(incoming);
        self
    }
    fn to_update_changes(&self) -> Result<ArticleChanges> {
        let mut changes = ArticleChanges::default();
        for ((col, bind), mode) in self.state.set_cols.iter().zip(self.state.set_binds.iter()).zip(self.state.set_modes.iter()) {
            match *col {
                "id" => {
                    let value = match bind {
            BindValue::I64(value) => value.clone(),
            other => anyhow::bail!("unexpected bind value '{:?}' for type 'i64'", other),
        };
                    changes.id = Some(match mode {
                        SetMode::Assign => FieldChange::Assign(value),
                        SetMode::Increment => FieldChange::Increment(value),
                        SetMode::Decrement => FieldChange::Decrement(value),
                    });
                }
                "author_id" => {
                    let value = match bind {
            BindValue::I64(value) => value.clone(),
            other => anyhow::bail!("unexpected bind value '{:?}' for type 'i64'", other),
        };
                    changes.author_id = Some(match mode {
                        SetMode::Assign => FieldChange::Assign(value),
                        SetMode::Increment => FieldChange::Increment(value),
                        SetMode::Decrement => FieldChange::Decrement(value),
                    });
                }
                "status" => {
                    let value = match bind {
                BindValue::String(value) => ArticleStatus::from_storage(value)
                    .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleStatus'", value))?,
                BindValue::I64(value) => {
                    let raw = value.to_string();
                    ArticleStatus::from_storage(&raw)
                        .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleStatus'", value))?
                }
                other => anyhow::bail!("unexpected bind value '{:?}' for type 'ArticleStatus'", other),
            };
                    changes.status = Some(match mode {
                        SetMode::Assign => FieldChange::Assign(value),
                        SetMode::Increment => FieldChange::Increment(value),
                        SetMode::Decrement => FieldChange::Decrement(value),
                    });
                }
                "is_system" => {
                    let value = match bind {
                BindValue::String(value) => ArticleSystemFlag::from_storage(value)
                    .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleSystemFlag'", value))?,
                BindValue::I64(value) => {
                    let raw = value.to_string();
                    ArticleSystemFlag::from_storage(&raw)
                        .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleSystemFlag'", value))?
                }
                other => anyhow::bail!("unexpected bind value '{:?}' for type 'ArticleSystemFlag'", other),
            };
                    changes.is_system = Some(match mode {
                        SetMode::Assign => FieldChange::Assign(value),
                        SetMode::Increment => FieldChange::Increment(value),
                        SetMode::Decrement => FieldChange::Decrement(value),
                    });
                }
                _ => {}
            }
        }
        Ok(changes)
    }


pub async fn save(self) -> Result<u64> {
        if self.state.set_cols.is_empty() { anyhow::bail!("update: no columns set"); }
        if self.state.where_sql.is_empty() { anyhow::bail!("update: no conditions set"); }
        let observer_changes = if try_get_observer().is_some() {
            Some(self.to_update_changes()?)
        } else {
            None
        };
        let db_conn = self.state.db.clone();
        match db_conn {
            DbConn::Pool(pool) => {
                let tx = pool.begin().await?;
                let tx_lock = std::sync::Arc::new(tokio::sync::Mutex::new(tx));
                let affected = {
                    let db = DbConn::tx(tx_lock.clone());
                    self.save_with_db(db, observer_changes.clone()).await?
                };
                let tx = std::sync::Arc::try_unwrap(tx_lock)
                    .map_err(|_| anyhow::anyhow!("transaction scope still has active handles"))?
                    .into_inner();
                tx.commit().await?;
                Ok(affected)
            }
            DbConn::Tx(_) => self.save_with_db(db_conn, observer_changes).await,
        }
    }

    async fn save_with_db<'tx>(self, db: DbConn<'tx>, observer_changes: Option<ArticleChanges>) -> Result<u64> {
        let mut state = self.state;
        // find target ids for localized updates
        let select_sql = format!("SELECT id FROM articles WHERE {}", state.where_sql.join(" AND "));
        let mut select_q = sqlx::query_scalar::<_, i64>(&select_sql);
        for b in &state.where_binds { select_q = bind_scalar(select_q, b.clone()); }
        let target_ids = db.fetch_all_scalar(select_q).await?;
        let __observer_active = try_get_observer().is_some();
        let __old_rows: Vec<ArticleRow> = if __observer_active && !target_ids.is_empty() {
            let phs: Vec<String> = (1..=target_ids.len()).map(|i| format!("${}", i)).collect();
            let fetch_sql = format!("SELECT * FROM articles WHERE id IN ({})", phs.join(", "));
            let mut fq = sqlx::query_as::<_, ArticleRow>(&fetch_sql);
            for id in &target_ids { fq = fq.bind(id); }
            let rows: Vec<ArticleRow> = db.fetch_all(fq).await.unwrap_or_default();
            rows
        } else {
            Vec::new()
        };
        if !__old_rows.is_empty() {
            if let Some(observer) = try_get_observer() {
                if let Some(changes) = observer_changes.as_ref() {
                    let changes_data = serde_json::to_value(changes)?;
                    for old_row in &__old_rows {
                        let old_data = serde_json::to_value(old_row)?;
                        let event = ModelEvent { model: "article", table: "articles", record_key: Some(format!("{}", old_row.id)) };
                        observer.on_updating(&event, &old_data, &changes_data).await?;
                    }
                }
            }
        }
        let (sql, all_binds) = state.build_update_sql();
        let set_binds = &state.set_binds;
        let mut q = sqlx::query(&sql);
        let __profiler_binds = if is_sql_profiler_enabled() { all_binds.iter().map(|b| format!("{}", b)).collect::<Vec<_>>().join(", ") } else { String::new() };
        let __profiler_start = std::time::Instant::now();
        for b in &all_binds { q = bind_query(q, b.clone()); }
        let res = db.execute(q).await?;
        record_profiled_query("articles", "UPDATE", &sql, &__profiler_binds, __profiler_start.elapsed());
        if res.rows_affected() > 0 && !self.translations.is_empty() && !target_ids.is_empty() {
            let supported = localized::SUPPORTED_LOCALES;
            if let Some(map) = self.translations.get("title") {
                let mut filtered = HashMap::new();
                for (loc, val) in map {
                    if supported.contains(&loc.as_str()) { filtered.insert(loc.clone(), val.clone()); }
                }
                if !filtered.is_empty() {
                    for id in &target_ids {
                        localized::upsert_localized_many(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), "title", &filtered).await?;
                    }
                }
            }
        }
        if res.rows_affected() > 0 && !self.meta.is_empty() && !target_ids.is_empty() {
            for id in &target_ids {
                localized::upsert_meta_many(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), &self.meta).await?;
            }
        }
        if res.rows_affected() > 0 && !target_ids.is_empty() {
            for id in &target_ids {
                for field in &self.attachments_clear_single {
                    localized::clear_attachment_field(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), field).await?;
                }
                for (field, att) in &self.attachments_single {
                    localized::replace_single_attachment(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), field, att).await?;
                }
                for (field, list) in &self.attachments_multi {
                    localized::add_attachments(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), field, list).await?;
                }
                for (field, ids) in &self.attachments_delete_multi {
                    localized::delete_attachment_ids(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), field, ids).await?;
                }
            }
        }
        if !__old_rows.is_empty() && res.rows_affected() > 0 {
            if let Some(observer) = try_get_observer() {
                for old_row in &__old_rows {
                    let fetch_sql = format!("SELECT * FROM articles WHERE id = $1");
                    match db.fetch_optional(sqlx::query_as::<_, ArticleRow>(&fetch_sql).bind(old_row.id.clone())).await {
                        Ok(Some(new_row)) => {
                            match (serde_json::to_value(old_row), serde_json::to_value(&new_row)) {
                                (Ok(old_data), Ok(new_data)) => {
                                    let event = ModelEvent { model: "article", table: "articles", record_key: Some(format!("{}", old_row.id)) };
                                    if let Err(err) = observer.on_updated(&event, &old_data, &new_data).await {
                                        log_observer_error("updated", "article", &err);
                                    }
                                }
                                (Err(err), _) | (_, Err(err)) => log_observer_error("updated", "article", &err),
                            }
                        }
                        Ok(None) => {}
                        Err(err) => log_observer_error("updated", "article", &err),
                    }
                }
            }
        }
        Ok(res.rows_affected())
    }
}



pub struct ArticleTableAdapter;
impl ArticleTableAdapter {
    fn parse_col(name: &str) -> Option<ArticleDbCol> {
        match name {
            "id" => Some(ArticleDbCol::Id),
            "author_id" => Some(ArticleDbCol::AuthorId),
            "status" => Some(ArticleDbCol::Status),
            "is_system" => Some(ArticleDbCol::IsSystem),
            _ => None,
        }
    }
    fn parse_locale_field_for_relation(relation: &str, column: &str) -> Option<&'static str> {
        match (relation, column) {
            ("author__profile", "display_name") => Some("display_name"),
            _ => None,
        }
    }
    fn parse_locale_field(name: &str) -> Option<&'static str> {
        match name {
            "title" => Some("title"),
            _ => None,
        }
    }
    fn parse_like_col(name: &str) -> Option<ArticleDbCol> {
        match name {
            _ => None,
        }
    }
    fn parse_bind_for_col(name: &str, raw: &str) -> Option<BindValue> {
        match name {
            "id" => raw.trim().parse::<i64>().ok().map(Into::into),
            "author_id" => raw.trim().parse::<i64>().ok().map(Into::into),
            "status" => Some(Self::parse_bind(raw.trim())),
            "is_system" => Some(Self::parse_bind(raw.trim())),
            _ => None,
        }
    }
    fn parse_bind_for_relation(relation: &str, column: &str, raw: &str) -> Option<BindValue> {
        match (relation, column) {
            ("author", "id") => raw.trim().parse::<i64>().ok().map(Into::into),
            ("author", "name") => Some(raw.trim().to_string().into()),
            ("author", "profile_id") => raw.trim().parse::<i64>().ok().map(Into::into),
            ("author__profile", "id") => raw.trim().parse::<i64>().ok().map(Into::into),
            _ => None,
        }
    }
    fn parse_bind(raw: &str) -> BindValue {
        let trimmed = raw.trim();
        let lower = trimmed.to_ascii_lowercase(); if lower == "true" { return true.into(); } if lower == "false" { return false.into(); }
        if let Ok(v) = trimmed.parse::<i64>() { return v.into(); }
        if let Ok(v) = trimmed.parse::<rust_decimal::Decimal>() { return v.into(); }
        if let Ok(v) = trimmed.parse::<f64>() { return v.into(); }
        if let Ok(v) = uuid::Uuid::parse_str(trimmed) { return v.into(); }
        if let Some(v) = Self::parse_datetime(trimmed, false) { return v.into(); }
        trimmed.to_string().into()
    }
    fn parse_datetime(raw: &str, end_of_day: bool) -> Option<time::OffsetDateTime> {
        let trimmed = raw.trim();
        if let Ok(dt) = time::OffsetDateTime::parse(trimmed, &time::format_description::well_known::Rfc3339) { return Some(dt); }
        if trimmed.len() == 10 {
            let date = time::Date::parse(trimmed, &time::macros::format_description!("[year]-[month]-[day]")).ok()?;
            let t = if end_of_day { time::Time::from_hms(23, 59, 59).ok()? } else { time::Time::MIDNIGHT };
            return Some(date.with_time(t).assume_offset(time::UtcOffset::UTC));
        }
        None
    }
}
impl GeneratedTableAdapter for ArticleTableAdapter {
    type Query<'db> = Query<'db, ArticleModel>;
    type Row = ArticleRecord;
    fn model_key(&self) -> &'static str { "Article" }
    fn sortable_columns(&self) -> &'static [&'static str] { &["id", "author_id", "status", "is_system"] }
    fn timestamp_columns(&self) -> &'static [&'static str] { &[] }
    fn column_descriptors(&self) -> &'static [DataTableColumnDescriptor] {
        &[
            DataTableColumnDescriptor { name: "id", label: "ID", data_type: "i64", sortable: true, localized: false, filter_ops: &["eq", "gte", "lte"] },
            DataTableColumnDescriptor { name: "author_id", label: "Author ID", data_type: "i64", sortable: true, localized: false, filter_ops: &["eq", "gte", "lte"] },
            DataTableColumnDescriptor { name: "status", label: "Status", data_type: "ArticleStatus", sortable: true, localized: false, filter_ops: &["eq", "gte", "lte"] },
            DataTableColumnDescriptor { name: "is_system", label: "Is System", data_type: "ArticleSystemFlag", sortable: true, localized: false, filter_ops: &["eq", "gte", "lte"] },
            DataTableColumnDescriptor { name: "title", label: "Title", data_type: "String", sortable: false, localized: true, filter_ops: &["locale_eq", "locale_like"] },
        ]
    }
    fn relation_column_descriptors(&self) -> &'static [DataTableRelationColumnDescriptor] {
        &[
            DataTableRelationColumnDescriptor { relation: "author", column: "id", data_type: "i64", filter_ops: &["has_eq"] },
            DataTableRelationColumnDescriptor { relation: "author", column: "name", data_type: "String", filter_ops: &["has_eq", "has_like"] },
            DataTableRelationColumnDescriptor { relation: "author", column: "profile_id", data_type: "i64", filter_ops: &["has_eq"] },
            DataTableRelationColumnDescriptor { relation: "author__profile", column: "id", data_type: "i64", filter_ops: &["has_eq"] },
            DataTableRelationColumnDescriptor { relation: "author__profile", column: "display_name", data_type: "String", filter_ops: &["locale_has_eq", "locale_has_like"] },
        ]
    }
    fn filter_patterns(&self) -> &'static [&'static str] {
        &[
            "f-<col>",
            "f-like-<col>",
            "f-gte-<col>",
            "f-lte-<col>",
            "f-date-from-<col>",
            "f-date-to-<col>",
            "f-like-any-<col1|col2|...>",
            "f-any-<col1|col2|...>",
            "f-has-<relation>-<col>",
            "f-has-like-<relation>-<col>",
            "f-locale-<col>",
            "f-locale-like-<col>",
            "f-locale-has-<relation>-<col>",
            "f-locale-has-like-<relation>-<col>",
        ]
    }
    fn apply_auto_filter<'db>(&self, query: Query<'db, ArticleModel>, filter: &ParsedFilter, value: &str) -> anyhow::Result<Option<Query<'db, ArticleModel>>> where Self: 'db {
        let trimmed = value.trim();
        if trimmed.is_empty() { return Ok(Some(query)); }
        match filter {
            ParsedFilter::Eq { column } => {
                let Some(col) = Self::parse_col(column.as_str()) else { return Ok(None); };
                let Some(bind) = Self::parse_bind_for_col(column.as_str(), trimmed) else { return Ok(None); };
                Ok(Some(query.where_col(col, Op::Eq, bind)))
            }
            ParsedFilter::Like { column } => {
                let Some(col) = Self::parse_like_col(column.as_str()) else { return Ok(None); };
                Ok(Some(query.where_col(col, Op::Like, format!("%{}%", trimmed))))
            }
            ParsedFilter::Gte { column } => {
                let Some(col) = Self::parse_col(column.as_str()) else { return Ok(None); };
                let Some(bind) = Self::parse_bind_for_col(column.as_str(), trimmed) else { return Ok(None); };
                Ok(Some(query.where_col(col, Op::Ge, bind)))
            }
            ParsedFilter::Lte { column } => {
                let Some(col) = Self::parse_col(column.as_str()) else { return Ok(None); };
                let Some(bind) = Self::parse_bind_for_col(column.as_str(), trimmed) else { return Ok(None); };
                Ok(Some(query.where_col(col, Op::Le, bind)))
            }
            ParsedFilter::DateFrom { column } => {
                let Some(col) = Self::parse_col(column.as_str()) else { return Ok(None); };
                let Some(ts) = Self::parse_datetime(trimmed, false) else { return Ok(None); };
                Ok(Some(query.where_col(col, Op::Ge, ts)))
            }
            ParsedFilter::DateTo { column } => {
                let Some(col) = Self::parse_col(column.as_str()) else { return Ok(None); };
                let Some(ts) = Self::parse_datetime(trimmed, true) else { return Ok(None); };
                Ok(Some(query.where_col(col, Op::Le, ts)))
            }
            ParsedFilter::LocaleEq { column } => {
                let Some(field) = Self::parse_locale_field(column.as_str()) else { return Ok(None); };
                let locale = core_i18n::current_locale().to_string();
                let clause = "EXISTS (SELECT 1 FROM localized l WHERE l.owner_type = ? AND l.owner_id = articles.id AND l.field = ? AND l.locale = ? AND l.value = ?)".to_string();
                Ok(Some(query.where_exists_raw(clause, vec![localized::ARTICLE_OWNER_TYPE.to_string(), field.to_string(), locale, trimmed.to_string()])))
            }
            ParsedFilter::LocaleLike { column } => {
                let Some(field) = Self::parse_locale_field(column.as_str()) else { return Ok(None); };
                let locale = core_i18n::current_locale().to_string();
                let pattern = format!("%{}%", trimmed);
                let clause = "EXISTS (SELECT 1 FROM localized l WHERE l.owner_type = ? AND l.owner_id = articles.id AND l.field = ? AND l.locale = ? AND l.value LIKE ?)".to_string();
                Ok(Some(query.where_exists_raw(clause, vec![localized::ARTICLE_OWNER_TYPE.to_string(), field.to_string(), locale, pattern])))
            }
            ParsedFilter::LikeAny { columns } => {
                let mut applied = false;
                let pattern = format!("%{}%", trimmed);
                let next = query.where_group(|group| {
                    let mut q = group;
                    for column in columns {
                        if let Some(col) = Self::parse_like_col(column.as_str()) {
                            if applied { q = q.or_where_col(col, Op::Like, pattern.clone()); } else { q = q.where_col(col, Op::Like, pattern.clone()); applied = true; }
                        }
                    }
                    q
                });
                if applied { Ok(Some(next)) } else { Ok(None) }
            }
            ParsedFilter::Any { columns } => {
                let mut applied = false;
                let next = query.where_group(|group| {
                    let mut q = group;
                    for column in columns {
                        if let Some(col) = Self::parse_col(column.as_str()) {
                            if let Some(bind) = Self::parse_bind_for_col(column.as_str(), trimmed) { if applied { q = q.or_where_col(col, Op::Eq, bind.clone()); } else { q = q.where_col(col, Op::Eq, bind.clone()); applied = true; } }
                        }
                    }
                    q
                });
                if applied { Ok(Some(next)) } else { Ok(None) }
            }
            ParsedFilter::Has { relation, column } => {
                match (relation.as_str(), column.as_str()) {
                    ("author", "id") => { let Some(bind) = Self::parse_bind_for_relation("author", "id", trimmed) else { return Ok(None); }; Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| rq.where_col(UserDbCol::Id, Op::Eq, bind)))) },
                    ("author", "name") => { let Some(bind) = Self::parse_bind_for_relation("author", "name", trimmed) else { return Ok(None); }; Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| rq.where_col(UserDbCol::Name, Op::Eq, bind)))) },
                    ("author", "profile_id") => { let Some(bind) = Self::parse_bind_for_relation("author", "profile_id", trimmed) else { return Ok(None); }; Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| rq.where_col(UserDbCol::ProfileId, Op::Eq, bind)))) },
                    ("author__profile", "id") => { let Some(bind) = Self::parse_bind_for_relation("author__profile", "id", trimmed) else { return Ok(None); }; Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| rq.where_has(UserRel::PROFILE, |rq| rq.where_col(ProfileDbCol::Id, Op::Eq, bind))))) },
                    _ => Ok(None),
                }
            }
            ParsedFilter::HasLike { relation, column } => {
                let pattern = format!("%{}%", trimmed);
                match (relation.as_str(), column.as_str()) {
                    ("author", "name") => Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| rq.where_col(UserDbCol::Name, Op::Like, pattern.clone())))),
                    _ => Ok(None),
                }
            }
            ParsedFilter::LocaleHas { relation, column } => {
                let Some(field) = Self::parse_locale_field_for_relation(relation.as_str(), column.as_str()) else { return Ok(None); };
                let locale = core_i18n::current_locale().to_string();
                match (relation.as_str(), column.as_str()) {
                    ("author__profile", "display_name") => Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| rq.where_has(UserRel::PROFILE, |rq| rq.where_exists_raw("EXISTS (SELECT 1 FROM localized l WHERE l.owner_type = ? AND l.owner_id = profiles.id AND l.field = ? AND l.locale = ? AND l.value = ?)".to_string(), vec![localized::PROFILE_OWNER_TYPE.to_string(), field.to_string(), locale.clone(), trimmed.to_string()]))))),
                    _ => Ok(None),
                }
            }
            ParsedFilter::LocaleHasLike { relation, column } => {
                let Some(field) = Self::parse_locale_field_for_relation(relation.as_str(), column.as_str()) else { return Ok(None); };
                let locale = core_i18n::current_locale().to_string();
                let pattern = format!("%{}%", trimmed);
                match (relation.as_str(), column.as_str()) {
                    ("author__profile", "display_name") => Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| rq.where_has(UserRel::PROFILE, |rq| rq.where_exists_raw("EXISTS (SELECT 1 FROM localized l WHERE l.owner_type = ? AND l.owner_id = profiles.id AND l.field = ? AND l.locale = ? AND l.value LIKE ?)".to_string(), vec![localized::PROFILE_OWNER_TYPE.to_string(), field.to_string(), locale.clone(), pattern.clone()]))))),
                    _ => Ok(None),
                }
            }
        }
    }
    fn apply_sort<'db>(&self, query: Query<'db, ArticleModel>, column: &str, dir: SortDirection) -> anyhow::Result<Query<'db, ArticleModel>> where Self: 'db {
        let dir = match dir { SortDirection::Asc => OrderDir::Asc, SortDirection::Desc => OrderDir::Desc };
        let next = match column {
            "id" => query.order_by(ArticleDbCol::Id, dir),
            "author_id" => query.order_by(ArticleDbCol::AuthorId, dir),
            "status" => query.order_by(ArticleDbCol::Status, dir),
            "is_system" => query.order_by(ArticleDbCol::IsSystem, dir),
            _ => query,
        };
        Ok(next)
    }
    fn apply_cursor<'db>(&self, query: Query<'db, ArticleModel>, column: &str, dir: SortDirection, cursor: &str) -> anyhow::Result<Option<Query<'db, ArticleModel>>> where Self: 'db {
        let Some(col) = Self::parse_col(column) else { return Ok(None); };
        let Some(bind) = Self::parse_bind_for_col(column, cursor) else { return Ok(None); };
        let op = match dir { SortDirection::Asc => Op::Gt, SortDirection::Desc => Op::Lt };
        Ok(Some(query.where_col(col, op, bind)))
    }
    fn cursor_from_row(&self, row: &ArticleRecord, column: &str) -> Option<String> {
        match column {
            "id" => Some(row.id.to_string()),
            "author_id" => Some(row.author_id.to_string()),
            _ => None,
        }
    }
    fn count<'db>(&self, query: Query<'db, ArticleModel>) -> BoxFuture<'db, anyhow::Result<i64>> where Self: 'db {
        Box::pin(async move { query.count().await })
    }
    fn fetch_page<'db>(&self, query: Query<'db, ArticleModel>, page: i64, per_page: i64) -> BoxFuture<'db, anyhow::Result<Vec<ArticleRecord>>> where Self: 'db {
        Box::pin(async move { Ok(query.paginate(page, per_page).await?.data) })
    }
}
#[derive(Debug, Clone, Copy)]
pub struct ArticleDataTableConfig {
    pub default_sorting_column: &'static str,
    pub default_sorted: SortDirection,
    pub default_export_ignore_columns: &'static [&'static str],
    pub default_timestamp_columns: &'static [&'static str],
    pub default_unsortable: &'static [&'static str],
    pub default_row_per_page: Option<i64>,
}
impl Default for ArticleDataTableConfig {
    fn default() -> Self {
        Self {
            default_sorting_column: "id",
            default_sorted: SortDirection::Desc,
            default_export_ignore_columns: &["actions", "action"],
            default_timestamp_columns: &[],
            default_unsortable: &[],
            default_row_per_page: None,
        }
    }
}
pub trait ArticleDataTableHooks: Send + Sync + 'static {
    fn scope<'db>(&'db self, query: Query<'db, ArticleModel>, _input: &DataTableInput, _ctx: &DataTableContext) -> Query<'db, ArticleModel> { query }
    fn authorize(&self, _input: &DataTableInput, _ctx: &DataTableContext) -> anyhow::Result<bool> { Ok(true) }
    fn filter_query<'db>(&'db self, _query: Query<'db, ArticleModel>, _filter_key: &str, _value: &str, _input: &DataTableInput, _ctx: &DataTableContext) -> anyhow::Result<Option<Query<'db, ArticleModel>>> { Ok(None) }
    fn filters<'db>(&'db self, query: Query<'db, ArticleModel>, _input: &DataTableInput, _ctx: &DataTableContext) -> anyhow::Result<Query<'db, ArticleModel>> { Ok(query) }
    fn map_row(&self, _row: &mut ArticleRecord, _input: &DataTableInput, _ctx: &DataTableContext) -> anyhow::Result<()> { Ok(()) }
    fn default_row_to_record(&self, row: ArticleRecord) -> anyhow::Result<serde_json::Map<String, serde_json::Value>> {
        let value = serde_json::to_value(&row)?;
        let mut record = match value { serde_json::Value::Object(map) => map, _ => anyhow::bail!("Generated row must serialize to a JSON object"), };
        if let Some(id_value) = record.get("id").cloned() {
            let id_text = match id_value {
                serde_json::Value::Number(number) => number.to_string(),
                serde_json::Value::String(text) => text,
                other => other.to_string(),
            };
            record.insert("id".to_string(), serde_json::Value::String(id_text));
        }
        Ok(record)
    }
    fn row_to_record(&self, row: ArticleRecord, _input: &DataTableInput, _ctx: &DataTableContext) -> anyhow::Result<serde_json::Map<String, serde_json::Value>> {
        self.default_row_to_record(row)
    }
    fn summary<'db>(&'db self, _query: Query<'db, ArticleModel>, _input: &DataTableInput, _ctx: &DataTableContext) -> BoxFuture<'db, anyhow::Result<Option<serde_json::Value>>> { Box::pin(async { Ok(None) }) }
}
#[derive(Default)]
pub struct ArticleDefaultDataTableHooks;
impl ArticleDataTableHooks for ArticleDefaultDataTableHooks {}
pub struct ArticleDataTable<H = ArticleDefaultDataTableHooks> where H: ArticleDataTableHooks {
    pub db: sqlx::PgPool,
    pub hooks: H,
    pub config: ArticleDataTableConfig,
    adapter: ArticleTableAdapter,
}
impl ArticleDataTable<ArticleDefaultDataTableHooks> {
    pub fn new(db: sqlx::PgPool) -> Self {
        Self {
            db,
            hooks: ArticleDefaultDataTableHooks,
            config: ArticleDataTableConfig::default(),
            adapter: ArticleTableAdapter,
        }
    }
}
impl<H: ArticleDataTableHooks> ArticleDataTable<H> {
    pub fn with_hooks<NH: ArticleDataTableHooks>(self, hooks: NH) -> ArticleDataTable<NH> {
        ArticleDataTable {
            db: self.db,
            hooks,
            config: self.config,
            adapter: ArticleTableAdapter,
        }
    }
    pub fn with_config(mut self, config: ArticleDataTableConfig) -> Self {
        self.config = config;
        self
    }
}
impl<H: ArticleDataTableHooks> AutoDataTable for ArticleDataTable<H> {
    type Adapter = ArticleTableAdapter;
    fn adapter(&self) -> &Self::Adapter { &self.adapter }
    fn base_query<'db>(&'db self, input: &DataTableInput, ctx: &DataTableContext) -> Query<'db, ArticleModel> {
        self.hooks.scope(ArticleModel::query(&self.db), input, ctx)
    }
    fn authorize(&self, input: &DataTableInput, ctx: &DataTableContext) -> anyhow::Result<bool> { self.hooks.authorize(input, ctx) }
    fn filter_query<'db>(&'db self, query: Query<'db, ArticleModel>, filter_key: &str, value: &str, input: &DataTableInput, ctx: &DataTableContext) -> anyhow::Result<Option<Query<'db, ArticleModel>>> { self.hooks.filter_query(query, filter_key, value, input, ctx) }
    fn filters<'db>(&'db self, query: Query<'db, ArticleModel>, input: &DataTableInput, ctx: &DataTableContext) -> anyhow::Result<Query<'db, ArticleModel>> { self.hooks.filters(query, input, ctx) }
    fn map_row(&self, row: &mut ArticleRecord, input: &DataTableInput, ctx: &DataTableContext) -> anyhow::Result<()> { self.hooks.map_row(row, input, ctx) }
    fn row_to_record(&self, row: ArticleRecord, input: &DataTableInput, ctx: &DataTableContext) -> anyhow::Result<serde_json::Map<String, serde_json::Value>> { self.hooks.row_to_record(row, input, ctx) }
    fn summary<'db>(&'db self, query: Query<'db, ArticleModel>, input: &DataTableInput, ctx: &DataTableContext) -> BoxFuture<'db, anyhow::Result<Option<serde_json::Value>>> where Self: 'db { self.hooks.summary(query, input, ctx) }
    fn default_sorting_column(&self) -> &'static str { self.config.default_sorting_column }
    fn default_sorted(&self) -> SortDirection { self.config.default_sorted }
    fn default_export_ignore_columns(&self) -> &'static [&'static str] { self.config.default_export_ignore_columns }
    fn default_timestamp_columns(&self) -> &'static [&'static str] { self.config.default_timestamp_columns }
    fn default_unsortable(&self) -> &'static [&'static str] { self.config.default_unsortable }
    fn default_row_per_page(&self, ctx: &DataTableContext) -> i64 { self.config.default_row_per_page.unwrap_or(ctx.default_per_page) }
}
use core_db::common::active_record::ActiveRecord;
#[async_trait::async_trait]
impl ActiveRecord for ArticleRecord {
    type Id = i64;
    async fn find(db: &sqlx::PgPool, id: Self::Id) -> anyhow::Result<Option<Self>> {
        ArticleModel::find(db, id).await.map_err(|e| e.into())
    }
}
pub struct ArticleModel;
impl ArticleModel {
    pub const TABLE: &'static str = "articles";
    pub const MODEL_KEY: &'static str = "article";
    pub const PK: &'static str = "id";
    pub fn query<'db>(db: impl Into<DbConn<'db>>) -> Query<'db, ArticleModel> {
        Query::new(db)
    }
    pub fn query_with_base_url<'db>(db: impl Into<DbConn<'db>>, base_url: Option<String>) -> Query<'db, ArticleModel> {
        Query::new_with_base_url(db, base_url)
    }
    pub fn create<'db>(db: impl Into<DbConn<'db>>) -> Create<'db, ArticleModel> {
        Create::new(db)
    }
    pub fn create_with_base_url<'db>(db: impl Into<DbConn<'db>>, base_url: Option<String>) -> Create<'db, ArticleModel> {
        Create::new_with_base_url(db, base_url)
    }
    pub fn patch<'db>(db: impl Into<DbConn<'db>>) -> Patch<'db, ArticleModel> {
        Patch::new(db)
    }
    pub fn patch_with_base_url<'db>(db: impl Into<DbConn<'db>>, base_url: Option<String>) -> Patch<'db, ArticleModel> {
        Patch::new_with_base_url(db, base_url)
    }
    pub async fn find<'db>(db: impl Into<DbConn<'db>>, id: i64) -> Result<Option<ArticleRecord>> {
        Query::<ArticleModel>::new(db).find(id).await
    }
}

impl ModelDef for ArticleModel {
    type Pk = i64;
    type Record = ArticleRecord;
    type Create = ArticleCreate;
    type Changes = ArticleChanges;
    const TABLE: &'static str = ArticleModel::TABLE;
    const MODEL_KEY: &'static str = ArticleModel::MODEL_KEY;
    const PK_COL: &'static str = "id";
}

impl core_db::common::model_api::QueryModel for ArticleModel {
    type InnerQuery<'db> = QueryState<'db>;
    fn query_root<'db>(db: DbConn<'db>, base_url: Option<String>) -> Self::InnerQuery<'db> {
        QueryState::new(db, base_url, "id, author_id, status, is_system")
    }
    fn query_all<'db>(state: Self::InnerQuery<'db>) -> core_db::common::model_api::BoxModelFuture<'db, Vec<Self::Record>> {
        Box::pin(async move {
            let (sql, binds) = state.to_select_sql("articles", HAS_SOFT_DELETE, "");
            let __profiler_binds = if is_sql_profiler_enabled() { binds.iter().map(|b| format!("{}", b)).collect::<Vec<_>>().join(", ") } else { String::new() };
            let __profiler_start = std::time::Instant::now();
            let mut q = sqlx::query_as::<_, ArticleRow>(&sql);
            for b in binds { q = bind(q, b); }
            let rows = state.db.fetch_all(q).await?;
            record_profiled_query("articles", "SELECT", &sql, &__profiler_binds, __profiler_start.elapsed());
            let db = state.db.clone();
            let author = load_author(db.clone(), &rows).await?;
            let ids: Vec<i64> = rows.iter().map(|r| r.id.clone()).collect();
            let localized = localized::load_article_localized(db.clone(), &ids).await?;
            let meta_map = localized::load_article_meta(db.clone(), &ids).await?;
            let attachments = localized::load_article_attachments(db.clone(), &ids).await?;
            let mut out_vec = Vec::with_capacity(rows.len());
            for r in rows {
                let key = r.id.clone();
                let mut record = hydrate_record(r.clone(), &localized, &meta_map, &attachments, state.base_url.as_deref());
                record.author = author.get(&key).cloned().unwrap_or(None);
                out_vec.push(record);
            }
            Ok(out_vec)
        })
    }
    fn query_first<'db>(state: Self::InnerQuery<'db>) -> core_db::common::model_api::BoxModelFuture<'db, Option<Self::Record>> {
        Box::pin(async move {
            let mut v = Self::query_all(state.limit(1)).await?;
            Ok(v.pop())
        })
    }
    fn query_find<'db>(state: Self::InnerQuery<'db>, id: Self::Pk) -> core_db::common::model_api::BoxModelFuture<'db, Option<Self::Record>> {
        Box::pin(async move { Self::query_first(state.where_col_str("id", Op::Eq, id.into())).await })
    }
    fn query_count<'db>(state: Self::InnerQuery<'db>) -> core_db::common::model_api::BoxModelFuture<'db, i64> {
        Box::pin(async move {
            let (sql, binds) = state.to_count_sql("articles", HAS_SOFT_DELETE, "");
            let __profiler_binds = if is_sql_profiler_enabled() { binds.iter().map(|b| format!("{}", b)).collect::<Vec<_>>().join(", ") } else { String::new() };
            let __profiler_start = std::time::Instant::now();
            let mut q = sqlx::query_scalar::<_, i64>(&sql);
            for b in binds { q = bind_scalar(q, b); }
            let count = state.db.fetch_scalar(q).await?;
            record_profiled_query("articles", "COUNT", &sql, &__profiler_binds, __profiler_start.elapsed());
            Ok(count)
        })
    }
    fn query_delete<'db>(state: Self::InnerQuery<'db>) -> core_db::common::model_api::BoxModelFuture<'db, u64> {
        Box::pin(async move {
            if state.limit.is_some() {
                anyhow::bail!("delete() does not support limit; add where clauses");
            }
            let db = state.db;
            let mut where_sql = state.where_sql;
            let binds = state.binds;
            if where_sql.is_empty() { anyhow::bail!("delete(): no conditions set"); }
            let __profiler_binds = if is_sql_profiler_enabled() { binds.iter().map(|b| format!("{}", b)).collect::<Vec<_>>().join(", ") } else { String::new() };
            let __observer_active = try_get_observer().is_some();
            let __old_rows: Vec<ArticleRow> = if __observer_active {
                let select_sql = format!("SELECT * FROM articles WHERE {}", where_sql.join(" AND "));
                let mut fq = sqlx::query_as::<_, ArticleRow>(&select_sql);
                for b in &binds { fq = bind(fq, b.clone()); }
                let rows: Vec<ArticleRow> = db.fetch_all(fq).await.unwrap_or_default();
                rows
            } else {
                Vec::new()
            };
            if !__old_rows.is_empty() {
                if let Some(observer) = try_get_observer() {
                    for old_row in &__old_rows {
                        let old_data = serde_json::to_value(old_row)?;
                        let event = ModelEvent { model: "article", table: "articles", record_key: Some(format!("{}", old_row.id)) };
                        observer.on_deleting(&event, &old_data).await?;
                    }
                }
            }
            let mut sql = String::from("DELETE FROM articles");
            if !where_sql.is_empty() {
                sql.push_str(" WHERE ");
                sql.push_str(&where_sql.join(" AND "));
            }
            let __profiler_start = std::time::Instant::now();
            let mut q = sqlx::query(&sql);
            for b in binds { q = bind_query(q, b); }
            let res = db.execute(q).await?;
            record_profiled_query("articles", "DELETE", &sql, &__profiler_binds, __profiler_start.elapsed());
            if !__old_rows.is_empty() && res.rows_affected() > 0 {
                if let Some(observer) = try_get_observer() {
                    for old_row in &__old_rows {
                        let event = ModelEvent { model: "article", table: "articles", record_key: Some(format!("{}", old_row.id)) };
                        match serde_json::to_value(old_row) {
                            Ok(old_data) => {
                                if let Err(err) = observer.on_deleted(&event, &old_data).await {
                                    log_observer_error("deleted", "article", &err);
                                }
                            }
                            Err(err) => log_observer_error("deleted", "article", &err),
                        }
                    }
                }
            }
            Ok(res.rows_affected())
        })
    }
    fn query_paginate<'db>(state: Self::InnerQuery<'db>, page: i64, per_page: i64) -> core_db::common::model_api::BoxModelFuture<'db, core_db::common::model_api::Page<Self::Record>> {
        Box::pin(async move {
            let page = if page < 1 { 1 } else { page };
            let per_page = resolve_per_page(per_page);
            let (count_sql, count_binds) = state.to_count_sql("articles", HAS_SOFT_DELETE, "");
            let __profiler_binds = if is_sql_profiler_enabled() { count_binds.iter().map(|b| format!("{}", b)).collect::<Vec<_>>().join(", ") } else { String::new() };
            let __profiler_start = std::time::Instant::now();
            let mut count_q = sqlx::query_scalar::<_, i64>(&count_sql);
            for b in count_binds { count_q = bind_scalar(count_q, b); }
            let total: i64 = state.db.fetch_scalar(count_q).await?;
            record_profiled_query("articles", "COUNT", &count_sql, &__profiler_binds, __profiler_start.elapsed());
            let last_page = ((total + per_page - 1) / per_page).max(1);
            let current_page = page.min(last_page);
            let offset_val = (current_page - 1) * per_page;
            let mut state = state;
            state.offset = Some(offset_val);
            state.limit = Some(per_page);
            let (sql, binds) = state.to_select_sql("articles", HAS_SOFT_DELETE, "");
            let __profiler_start = std::time::Instant::now();
            let mut q = sqlx::query_as::<_, ArticleRow>(&sql);
            for b in binds { q = bind(q, b); }
            let rows = state.db.fetch_all(q).await?;
            record_profiled_query("articles", "SELECT", &sql, &__profiler_binds, __profiler_start.elapsed());
            let db = state.db.clone();
            let author = load_author(db.clone(), &rows).await?;
            let ids: Vec<i64> = rows.iter().map(|r| r.id.clone()).collect();
            let localized = localized::load_article_localized(db.clone(), &ids).await?;
            let meta_map = localized::load_article_meta(db.clone(), &ids).await?;
            let attachments = localized::load_article_attachments(db.clone(), &ids).await?;
            let mut data = Vec::with_capacity(rows.len());
            for r in rows {
                let key = r.id.clone();
                let mut record = hydrate_record(r.clone(), &localized, &meta_map, &attachments, state.base_url.as_deref());
                record.author = author.get(&key).cloned().unwrap_or(None);
                data.push(record);
            }
            Ok(core_db::common::model_api::Page { data, total, per_page, current_page, last_page })
        })
    }
    fn query_limit<'db>(state: Self::InnerQuery<'db>, limit: i64) -> Self::InnerQuery<'db> {
        state.limit(limit)
    }
    fn query_offset<'db>(state: Self::InnerQuery<'db>, offset: i64) -> Self::InnerQuery<'db> {
        state.offset(offset)
    }
    fn query_for_update<'db>(state: Self::InnerQuery<'db>) -> Self::InnerQuery<'db> {
        state.for_update()
    }
    fn query_for_update_skip_locked<'db>(state: Self::InnerQuery<'db>) -> Self::InnerQuery<'db> {
        state.for_update_skip_locked()
    }
    fn query_for_no_key_update<'db>(state: Self::InnerQuery<'db>) -> Self::InnerQuery<'db> {
        state.for_no_key_update()
    }
    fn query_where_group<'db, F>(state: Self::InnerQuery<'db>, scope: F) -> Self::InnerQuery<'db>
    where
        F: FnOnce(core_db::common::model_api::Query<'db, Self>) -> core_db::common::model_api::Query<'db, Self>,
    {
        state.where_group(|group| scope(core_db::common::model_api::Query::from_inner(group)).into_inner())
    }
    fn query_or_where_group<'db, F>(state: Self::InnerQuery<'db>, scope: F) -> Self::InnerQuery<'db>
    where
        F: FnOnce(core_db::common::model_api::Query<'db, Self>) -> core_db::common::model_api::Query<'db, Self>,
    {
        state.or_where_group(|group| scope(core_db::common::model_api::Query::from_inner(group)).into_inner())
    }
}

impl core_db::common::model_api::UnsafeQueryModel for ArticleModel {
    fn query_where_raw<'db>(state: Self::InnerQuery<'db>, clause: String, binds: Vec<BindValue>) -> Self::InnerQuery<'db> {
        state.where_raw(clause, binds)
    }
    fn query_where_exists<'db>(state: Self::InnerQuery<'db>, clause: String, binds: Vec<BindValue>) -> Self::InnerQuery<'db> {
        state.where_exists_raw(clause, binds)
    }
    fn query_order_raw<'db>(state: Self::InnerQuery<'db>, expr: String) -> Self::InnerQuery<'db> {
        state.order_raw(expr)
    }
    fn query_select_raw<'db>(state: Self::InnerQuery<'db>, expr: String) -> Self::InnerQuery<'db> {
        state.select_raw(expr)
    }
    fn query_join_raw<'db>(state: Self::InnerQuery<'db>, table: String, on_clause: String, binds: Vec<BindValue>) -> Self::InnerQuery<'db> {
        state.join_raw("INNER JOIN", table, on_clause, binds)
    }
}

impl core_db::common::model_api::CreateModel for ArticleModel {
    type InnerCreate<'db> = ArticleCreateInner<'db>;
    fn create_root<'db>(db: DbConn<'db>, base_url: Option<String>) -> Self::InnerCreate<'db> {
        ArticleCreateInner::new(db, base_url)
    }
    fn create_save<'db>(builder: Self::InnerCreate<'db>) -> core_db::common::model_api::BoxModelFuture<'db, Self::Record> {
        Box::pin(async move {
            let db = builder.state.db.clone();
            let base_url = builder.state.base_url.clone();
            let created = builder.save().await?;
            Query::<ArticleModel>::new_with_base_url(db, base_url).find(created.id.clone()).await?.ok_or_else(|| anyhow::anyhow!("articles: created record not found"))
        })
    }
}

impl core_db::common::model_api::CreateField<ArticleModel> for ArticleDbCol {
    type Value = BindValue;
    fn set<'db>(field: Self, mut builder: <ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db>, value: <Self as core_db::common::model_api::CreateField<ArticleModel>>::Value) -> anyhow::Result<<ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db>> {
        match field {
            ArticleDbCol::Id => {
                builder.state = builder.state.set_col(field.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::AuthorId => {
                builder.state = builder.state.set_col(field.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::Status => {
                builder.state = builder.state.set_col(field.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::IsSystem => {
                builder.state = builder.state.set_col(field.as_sql(), value);
                Ok(builder)
            }
        }
    }
}

impl<T> core_db::common::model_api::CreateField<ArticleModel> for Column<ArticleModel, T>
where
    T: Into<BindValue>,
{
    type Value = T;
    fn set<'db>(field: Self, mut builder: <ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db>, value: Self::Value) -> anyhow::Result<<ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db>> {
        let field = resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column");
        let value = value.into();
        match field {
            ArticleDbCol::Id => {
                builder.state = builder.state.set_col(field.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::AuthorId => {
                builder.state = builder.state.set_col(field.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::Status => {
                builder.state = builder.state.set_col(field.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::IsSystem => {
                builder.state = builder.state.set_col(field.as_sql(), value);
                Ok(builder)
            }
        }
    }
}

impl core_db::common::model_api::CreateConflictField<ArticleModel> for ArticleDbCol {
    fn on_conflict_do_nothing<'db>(builder: <ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db>, fields: &[Self]) -> <ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db> {
        builder.on_conflict_do_nothing(fields)
    }
    fn on_conflict_update<'db>(builder: <ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db>, fields: &[Self]) -> <ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db> {
        builder.on_conflict_update(fields)
    }
}

impl<T> core_db::common::model_api::CreateConflictField<ArticleModel> for Column<ArticleModel, T> {
    fn on_conflict_do_nothing<'db>(builder: <ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db>, fields: &[Self]) -> <ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db> {
        let fields: Vec<ArticleDbCol> = fields.iter().map(|field| resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column")).collect();
        builder.on_conflict_do_nothing(&fields)
    }
    fn on_conflict_update<'db>(builder: <ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db>, fields: &[Self]) -> <ArticleModel as core_db::common::model_api::CreateModel>::InnerCreate<'db> {
        let fields: Vec<ArticleDbCol> = fields.iter().map(|field| resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column")).collect();
        builder.on_conflict_update(&fields)
    }
}

impl core_db::common::model_api::PatchModel for ArticleModel {
    type InnerQuery<'db> = QueryState<'db>;
    type InnerPatch<'db> = ArticlePatchInner<'db>;
    fn patch_root<'db>(db: DbConn<'db>, base_url: Option<String>) -> Self::InnerPatch<'db> {
        ArticlePatchInner::new(db, base_url)
    }
    fn patch_from_query<'db>(mut state: Self::InnerQuery<'db>) -> Self::InnerPatch<'db> {
        let db = state.db.clone();
        let base_url = state.base_url.clone();
        state.select_sql = Some(ArticleDbCol::Id.as_sql().to_string());
        let (scope_sql, binds) = state.to_sql();
        let mut builder = ArticlePatchInner::new(db, base_url);
        builder.state.where_sql.push(format!("{} IN ({})", ArticleDbCol::Id.as_sql(), scope_sql));
        builder.state.where_binds = binds;
        builder
    }
    fn patch_save<'db>(builder: Self::InnerPatch<'db>) -> core_db::common::model_api::BoxModelFuture<'db, u64> {
        Box::pin(async move { builder.save().await })
    }
    fn patch_fetch<'db>(builder: Self::InnerPatch<'db>) -> core_db::common::model_api::BoxModelFuture<'db, Vec<Self::Record>> {
        Box::pin(async move {
            if builder.state.where_sql.is_empty() {
                anyhow::bail!("update: no conditions set");
            }
            let db = builder.state.db.clone();
            let base_url = builder.state.base_url.clone();
            let mut select_sql = format!("SELECT {} FROM articles", ArticleDbCol::Id.as_sql());
            select_sql.push_str(&format!(" WHERE {}", builder.state.where_sql.join(" AND ")));
            let mut select_q = sqlx::query_scalar::<_, i64>(&select_sql);
            for bind_value in &builder.state.where_binds { select_q = bind_scalar(select_q, bind_value.clone()); }
            let target_ids = db.fetch_all_scalar(select_q).await?;
            builder.save().await?;
            if target_ids.is_empty() {
                return Ok(Vec::new());
            }
            let mut query = Query::<ArticleModel>::new_with_base_url(db, base_url);
            let binds: Vec<BindValue> = target_ids.iter().cloned().map(Into::into).collect();
            let state = query.into_inner().where_in_str(ArticleDbCol::Id.as_sql(), &binds);
            <Self as core_db::common::model_api::QueryModel>::query_all(state).await
        })
    }
}

impl core_db::common::model_api::PatchAssignField<ArticleModel> for ArticleDbCol {
    type Value = BindValue;
    fn assign<'db>(field: Self, mut builder: <ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>, value: <Self as core_db::common::model_api::PatchAssignField<ArticleModel>>::Value) -> anyhow::Result<<ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>> {
        match field {
            ArticleDbCol::Id => {
                builder.state = builder.state.assign_col(field.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::AuthorId => {
                builder.state = builder.state.assign_col(field.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::Status => {
                builder.state = builder.state.assign_col(field.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::IsSystem => {
                builder.state = builder.state.assign_col(field.as_sql(), value);
                Ok(builder)
            }
        }
    }
}

impl<T> core_db::common::model_api::PatchAssignField<ArticleModel> for Column<ArticleModel, T>
where
    T: Into<BindValue>,
{
    type Value = T;
    fn assign<'db>(field: Self, mut builder: <ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>, value: Self::Value) -> anyhow::Result<<ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>> {
        let resolved = resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column");
        let value = value.into();
        match resolved {
            ArticleDbCol::Id => {
                builder.state = builder.state.assign_col(resolved.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::AuthorId => {
                builder.state = builder.state.assign_col(resolved.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::Status => {
                builder.state = builder.state.assign_col(resolved.as_sql(), value);
                Ok(builder)
            }
            ArticleDbCol::IsSystem => {
                builder.state = builder.state.assign_col(resolved.as_sql(), value);
                Ok(builder)
            }
        }
    }
}

impl core_db::common::model_api::PatchNumericField<ArticleModel> for ArticleDbCol {
    fn increment<'db>(field: Self, mut builder: <ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>, value: <Self as core_db::common::model_api::PatchAssignField<ArticleModel>>::Value) -> anyhow::Result<<ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>> {
        match field {
            ArticleDbCol::Id => { builder.state = builder.state.increment_col(field.as_sql(), value); Ok(builder) }
            ArticleDbCol::AuthorId => { builder.state = builder.state.increment_col(field.as_sql(), value); Ok(builder) }
            _ => anyhow::bail!("column '{}' does not support increment", field.as_sql()),
        }
    }
    fn decrement<'db>(field: Self, mut builder: <ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>, value: <Self as core_db::common::model_api::PatchAssignField<ArticleModel>>::Value) -> anyhow::Result<<ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>> {
        match field {
            ArticleDbCol::Id => { builder.state = builder.state.decrement_col(field.as_sql(), value); Ok(builder) }
            ArticleDbCol::AuthorId => { builder.state = builder.state.decrement_col(field.as_sql(), value); Ok(builder) }
            _ => anyhow::bail!("column '{}' does not support decrement", field.as_sql()),
        }
    }
}

impl core_db::common::model_api::PatchNumericField<ArticleModel> for Column<ArticleModel, i64> {
    fn increment<'db>(field: Self, mut builder: <ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>, value: <Self as core_db::common::model_api::PatchAssignField<ArticleModel>>::Value) -> anyhow::Result<<ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>> {
        let resolved = resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column");
        match resolved {
            ArticleDbCol::Id => { builder.state = builder.state.increment_col(resolved.as_sql(), value.into()); Ok(builder) }
            ArticleDbCol::AuthorId => { builder.state = builder.state.increment_col(resolved.as_sql(), value.into()); Ok(builder) }
            _ => anyhow::bail!("column '{}' does not support increment", resolved.as_sql()),
        }
    }
    fn decrement<'db>(field: Self, mut builder: <ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>, value: <Self as core_db::common::model_api::PatchAssignField<ArticleModel>>::Value) -> anyhow::Result<<ArticleModel as core_db::common::model_api::PatchModel>::InnerPatch<'db>> {
        let resolved = resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column");
        match resolved {
            ArticleDbCol::Id => { builder.state = builder.state.decrement_col(resolved.as_sql(), value.into()); Ok(builder) }
            ArticleDbCol::AuthorId => { builder.state = builder.state.decrement_col(resolved.as_sql(), value.into()); Ok(builder) }
            _ => anyhow::bail!("column '{}' does not support decrement", resolved.as_sql()),
        }
    }
}

impl core_db::common::model_api::QueryField<ArticleModel> for ArticleDbCol {
    type Value = BindValue;
    fn where_col<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>, op: Op, value: <Self as core_db::common::model_api::QueryField<ArticleModel>>::Value) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        state.where_col_str(field.as_sql(), op, value)
    }
    fn or_where_col<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>, op: Op, value: <Self as core_db::common::model_api::QueryField<ArticleModel>>::Value) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        state.or_where_col_str(field.as_sql(), op, value)
    }
    fn where_in<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>, values: &[<Self as core_db::common::model_api::QueryField<ArticleModel>>::Value]) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        state.where_in_str(field.as_sql(), values)
    }
    fn order_by<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>, dir: OrderDir) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        state.order_by_str(field.as_sql(), dir)
    }
    fn where_null<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        state.where_null_str(field.as_sql())
    }
    fn where_not_null<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        state.where_not_null_str(field.as_sql())
    }
}

impl<T> core_db::common::model_api::QueryField<ArticleModel> for Column<ArticleModel, T>
where
    T: Clone + Into<BindValue>,
{
    type Value = T;
    fn where_col<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>, op: Op, value: Self::Value) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        let col = resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column");
        state.where_col_str(col.as_sql(), op, value.into())
    }
    fn or_where_col<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>, op: Op, value: Self::Value) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        let col = resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column");
        state.or_where_col_str(col.as_sql(), op, value.into())
    }
    fn where_in<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>, values: &[Self::Value]) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        let col = resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column");
        let bind_values: Vec<BindValue> = values.iter().map(|v| v.clone().into()).collect();
        state.where_in_str(col.as_sql(), &bind_values)
    }
    fn order_by<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>, dir: OrderDir) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        let col = resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column");
        state.order_by_str(col.as_sql(), dir)
    }
    fn where_null<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        let col = resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column");
        state.where_null_str(col.as_sql())
    }
    fn where_not_null<'db>(field: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        let col = resolve_article_db_col(field.as_sql()).expect("typed generated column must resolve to an internal db column");
        state.where_not_null_str(col.as_sql())
    }
}

impl core_db::common::model_api::IncludeRelation<ArticleModel> for OneRelation<ArticleModel, UserRow, 0> {
    fn include<'db>(_relation: Self, state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db> {
        state
    }
}

impl core_db::common::model_api::WhereHasRelation<ArticleModel> for OneRelation<ArticleModel, UserRow, 0> {
    type Target = UserModel;
    fn where_has<'db, F>(_relation: Self, mut state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>, scope: F) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>
    where
        F: FnOnce(Query<'db, Self::Target>) -> Query<'db, Self::Target>,
    {
        let start_idx = state.binds.len() + 1;
        let scoped = scope(UserModel::query_with_base_url(state.db.clone(), None));
        let (mut sub_where, sub_binds) = scoped.into_inner().into_where_parts();
        sub_where.insert(0, "users.id = articles.author_id".to_string());
        let mut clause = String::from("EXISTS (SELECT 1 FROM users WHERE ");
        clause.push_str(&sub_where.join(" AND "));
        clause.push(')');
        let clause = renumber_placeholders(&clause, start_idx);
        state.where_sql.push(clause);
        state.binds.extend(sub_binds);
        state
    }
    fn or_where_has<'db, F>(_relation: Self, mut state: <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>, scope: F) -> <ArticleModel as core_db::common::model_api::QueryModel>::InnerQuery<'db>
    where
        F: FnOnce(Query<'db, Self::Target>) -> Query<'db, Self::Target>,
    {
        let start_idx = state.binds.len() + 1;
        let scoped = scope(UserModel::query_with_base_url(state.db.clone(), None));
        let (mut sub_where, sub_binds) = scoped.into_inner().into_where_parts();
        sub_where.insert(0, "users.id = articles.author_id".to_string());
        let mut clause = String::from("EXISTS (SELECT 1 FROM users WHERE ");
        clause.push_str(&sub_where.join(" AND "));
        clause.push(')');
        let clause = renumber_placeholders(&clause, start_idx);
        if let Some(last) = state.where_sql.pop() {
            state.where_sql.push(format!("({} OR {})", last, clause));
        } else {
            state.where_sql.push(clause);
        }
        state.binds.extend(sub_binds);
        state
    }
}

impl core_db::common::model_api::RecordOneRelation<ArticleModel> for OneRelation<ArticleModel, UserRow, 0> {
    type Target = UserRow;
    fn get<'a>(_relation: Self, record: &'a ArticleRecord) -> Option<&'a Self::Target> {
        record.author.as_ref()
    }
}


