// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by build.rs from Rust model sources + configs.toml
#![allow(dead_code, unused_imports, unused_variables, unused_mut)]
use anyhow::Result;
use std::collections::HashMap;
use serde_json::Value as JsonValue;
use serde::{Deserialize, Serialize};
use schemars::JsonSchema;
use sqlx::FromRow;
use core_db::common::sql::{BindValue, Op, OrderDir, SetMode, bind, bind_query, bind_scalar, generate_snowflake_i64, is_sql_profiler_enabled, format_duration, record_profiled_query, DbConn};
use core_db::common::pagination::resolve_per_page;
use core_datatable::{AutoDataTable, BoxFuture, DataTableColumnDescriptor, DataTableColumnResolver, DataTableContext, DataTableInput, DataTableRelationColumnDescriptor, GeneratedTableAdapter, ParsedFilter, SortDirection};
use core_db::platform::attachments::types::{Attachment, AttachmentInput, AttachmentMap};
use uuid::Uuid;
use core_db::platform::localized::types::LocalizedMap;
use crate::generated::models::common::{FieldChange, FieldInput, Page, log_observer_error, renumber_placeholders};
use core_db::common::model_api::{ColExpr, Column, Create, CreateState, ManyRelation, ModelDef, OneRelation, Patch, PatchState, Query, QueryState};
use core_db::platform::meta::types::MetaMap;
use crate::generated::localized;
use core_i18n::current_locale;
use crate::generated::models::user::{UserDbCol, UserModel, UserRecord, UserRow, UserRel};
use crate::generated::models::profile::{ProfileDbCol, ProfileModel, ProfileRecord, ProfileRow};
use crate::generated::localized::LocalizedMapHelper;
use super::enums::*;
use core_db::common::model_observer::{ModelEvent, ObserverAction, try_get_observer};
const HAS_CREATED_AT: bool = false;
const HAS_UPDATED_AT: bool = false;
const HAS_SOFT_DELETE: bool = false;
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[doc(hidden)]
pub struct ArticleCreate {
    pub id: FieldInput<i64>,
    pub author_id: FieldInput<i64>,
    pub status: FieldInput<ArticleStatus>,
    pub is_system: FieldInput<ArticleSystemFlag>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[doc(hidden)]
pub struct ArticleChanges {
    pub id: Option<FieldChange<i64>>,
    pub author_id: Option<FieldChange<i64>>,
    pub status: Option<FieldChange<ArticleStatus>>,
    pub is_system: Option<FieldChange<ArticleSystemFlag>>,
}

#[derive(Debug, Clone, FromRow, Serialize, Deserialize, JsonSchema)]
#[doc(hidden)]
pub struct ArticleRow {
    pub id: i64,
    pub author_id: i64,
    pub status: ArticleStatus,
    pub is_system: ArticleSystemFlag,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct ArticleRecord {
    pub id: i64,
    pub author_id: i64,
    pub status: ArticleStatus,
    pub is_system: ArticleSystemFlag,
    #[serde(default)]
    pub status_explained: String,
    #[serde(default)]
    pub is_system_explained: String,
    #[serde(default)]
    pub title: Option<String>,
    #[serde(default)]
    pub title_translations: Option<localized::LocalizedText>,
    #[serde(default)]
    pub hero: Option<Attachment>,
    #[serde(default)]
    pub hero_url: Option<String>,
    #[serde(default)]
    pub meta: std::collections::HashMap<String, JsonValue>,
    #[serde(default)]
    pub author: Option<Box<UserRecord>>,
    #[serde(skip)]
    #[schemars(skip)]
    pub __relation_counts: std::collections::HashMap<String, i64>,
    #[serde(skip)]
    #[schemars(skip)]
    pub __relation_aggregates: std::collections::HashMap<String, f64>,
}

impl ArticleRecord {
    pub fn update<'db>(&self) -> Patch<'db, ArticleModel> {
        ArticleModel::query().where_col(ArticleDbCol::Id, Op::Eq, self.id.clone()).patch()
    }
    pub fn meta_flags(&self) -> Option<bool> { self.meta.get("flags").and_then(|v| v.as_bool()) }
    pub fn meta_extra_as<T: serde::de::DeserializeOwned>(&self) -> anyhow::Result<Option<T>> { match self.meta.get("extra") { None => Ok(None), Some(v) => Ok(Some(serde_json::from_value(v.clone())?)), } }
    pub async fn upsert_title<'a>(&self, db: DbConn<'a>, input: Option<localized::LocalizedInput>) -> Result<()> {
        let Some(input) = input else { return Ok(()); };
        if input.is_empty() { return Ok(()); }
        let map = input.to_hashmap();
        localized::upsert_localized_many(db, localized::ARTICLE_OWNER_TYPE, self.id, "title", &map).await
    }
    pub async fn clear_title<'a>(&self, db: DbConn<'a>) -> Result<()> {
        localized::delete_localized_field(db, localized::ARTICLE_OWNER_TYPE, self.id, "title").await
    }
}

pub(crate) fn hydrate_record(row: ArticleRow, loc: &LocalizedMap, meta: &MetaMap, attachments: &AttachmentMap, base_url: Option<&str>) -> ArticleRecord {
    let locale = current_locale();
    let mut record = ArticleRecord {
        id: row.id,
        author_id: row.author_id,
        status: row.status,
        is_system: row.is_system,
        status_explained: row.status.explained_label(),
        is_system_explained: row.is_system.explained_label(),
        title: None,
        title_translations: None,
        hero: None,
        hero_url: None,
        meta: HashMap::new(),
        author: None,
        __relation_counts: HashMap::new(),
        __relation_aggregates: HashMap::new(),
    };
    let ml_title = loc.get_localized_text("title", record.id);
    if let Some(ref ml) = ml_title {
        record.title = Some(ml.get(locale).to_string());
    }
    record.title_translations = ml_title;
    record.meta = meta.get_all_for_owner(record.id);
    record.hero = attachments.get_single("hero", record.id);
    record.hero_url = record.hero.as_ref().map(|a| a.url_with_base(base_url));
    record
}

pub(crate) async fn hydrate_records<'db>(db: DbConn<'db>, rows: &[ArticleRow], base_url: Option<&str>) -> Result<Vec<ArticleRecord>> {
    if rows.is_empty() { return Ok(Vec::new()); }
        let ids: Vec<i64> = rows.iter().map(|r| r.id.clone()).collect();
        let localized = localized::load_article_localized(db.clone(), &ids).await?;
        let meta_map = localized::load_article_meta(db.clone(), &ids).await?;
        let attachments = localized::load_article_attachments(db.clone(), &ids).await?;
    let mut records = Vec::with_capacity(rows.len());
    for row in rows {
        records.push(hydrate_record(row.clone(), &localized, &meta_map, &attachments, base_url));
    }
    Ok(records)
}

impl core_db::common::model_api::RelationMetricRecord for ArticleRecord {
    fn relation_counts(&self) -> &std::collections::HashMap<String, i64> {
        &self.__relation_counts
    }
    fn relation_aggregates(&self) -> &std::collections::HashMap<String, f64> {
        &self.__relation_aggregates
    }
    fn relation_counts_mut(&mut self) -> &mut std::collections::HashMap<String, i64> {
        &mut self.__relation_counts
    }
    fn relation_aggregates_mut(&mut self) -> &mut std::collections::HashMap<String, f64> {
        &mut self.__relation_aggregates
    }
}

impl ArticleRecord {
    pub fn one<R>(&self, relation: R) -> Option<&R::Target>
    where
        R: core_db::common::model_api::RecordOneRelation<ArticleModel>,
    {
        R::get(relation, self)
    }
    pub fn many<R>(&self, relation: R) -> &[R::Target]
    where
        R: core_db::common::model_api::RecordManyRelation<ArticleModel>,
    {
        R::get(relation, self)
    }
    pub fn count<R>(&self, relation: R) -> Option<i64>
    where
        R: core_db::common::model_api::CountRelation<ArticleModel>,
    {
        self.__relation_counts.get(R::name(relation)).copied()
    }
    pub fn sum<R, A>(&self, relation: R, target: A) -> Option<f64>
    where
        R: core_db::common::model_api::CountRelation<ArticleModel>,
        A: Into<core_db::common::model_api::AggregateTarget<R::TargetModel>>,
    {
        let key = core_db::common::model_api::relation_aggregate_lookup_key(
            R::name(relation),
            core_db::common::model_api::RelationAggregateKind::Sum,
            &target.into().into_spec(),
        );
        self.__relation_aggregates.get(&key).copied()
    }
    pub fn avg<R, A>(&self, relation: R, target: A) -> Option<f64>
    where
        R: core_db::common::model_api::CountRelation<ArticleModel>,
        A: Into<core_db::common::model_api::AggregateTarget<R::TargetModel>>,
    {
        let key = core_db::common::model_api::relation_aggregate_lookup_key(
            R::name(relation),
            core_db::common::model_api::RelationAggregateKind::Avg,
            &target.into().into_spec(),
        );
        self.__relation_aggregates.get(&key).copied()
    }
    pub fn min<R, A>(&self, relation: R, target: A) -> Option<f64>
    where
        R: core_db::common::model_api::CountRelation<ArticleModel>,
        A: Into<core_db::common::model_api::AggregateTarget<R::TargetModel>>,
    {
        let key = core_db::common::model_api::relation_aggregate_lookup_key(
            R::name(relation),
            core_db::common::model_api::RelationAggregateKind::Min,
            &target.into().into_spec(),
        );
        self.__relation_aggregates.get(&key).copied()
    }
    pub fn max<R, A>(&self, relation: R, target: A) -> Option<f64>
    where
        R: core_db::common::model_api::CountRelation<ArticleModel>,
        A: Into<core_db::common::model_api::AggregateTarget<R::TargetModel>>,
    {
        let key = core_db::common::model_api::relation_aggregate_lookup_key(
            R::name(relation),
            core_db::common::model_api::RelationAggregateKind::Max,
            &target.into().into_spec(),
        );
        self.__relation_aggregates.get(&key).copied()
    }
    pub fn aggregate(&self, key: &str) -> Option<f64> {
        self.__relation_aggregates.get(key).copied()
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ArticleCol;
impl ArticleCol {
    pub const ID: Column<ArticleModel, i64> = Column::new("id");
    pub const AUTHOR_ID: Column<ArticleModel, i64> = Column::new("author_id");
    pub const STATUS: Column<ArticleModel, ArticleStatus> = Column::new("status");
    pub const IS_SYSTEM: Column<ArticleModel, ArticleSystemFlag> = Column::new("is_system");
}

fn resolve_article_db_col(sql: &str) -> Option<ArticleDbCol> {
    match sql {
        "id" => Some(ArticleDbCol::Id),
        "author_id" => Some(ArticleDbCol::AuthorId),
        "status" => Some(ArticleDbCol::Status),
        "is_system" => Some(ArticleDbCol::IsSystem),
        _ => None,
    }
}

#[derive(Debug, Clone, Copy, JsonSchema)]
pub enum ArticleDbCol {
    Id,
    AuthorId,
    Status,
    IsSystem,
}

impl ArticleDbCol {
    pub const fn all() -> &'static [ArticleDbCol] {
        &[ArticleDbCol::Id, ArticleDbCol::AuthorId, ArticleDbCol::Status, ArticleDbCol::IsSystem]
    }
    pub const fn as_sql(self) -> &'static str {
        match self {
            ArticleDbCol::Id => "id",
            ArticleDbCol::AuthorId => "author_id",
            ArticleDbCol::Status => "status",
            ArticleDbCol::IsSystem => "is_system",
        }
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ArticleRel;
impl ArticleRel {
    pub const AUTHOR: OneRelation<ArticleModel, UserRecord, 0> = OneRelation::<ArticleModel, UserRecord, 0>::new("author");
}

fn rel_author_parent_key(record: &ArticleRecord) -> Option<i64> { Some(record.author_id.clone()) }
fn rel_author_target_key(record: &UserRecord) -> i64 { record.id.clone() }
fn rel_author_assign(record: &mut ArticleRecord, child: Option<UserRecord>) { record.author = child.map(Box::new); }
static REL_RUNTIME_AUTHOR: core_db::common::model_api::BelongsToRuntime<ArticleModel, UserModel, i64> = core_db::common::model_api::BelongsToRuntime {
    name: "author",
    target_table: "users",
    target_key_sql: "id",
    parent_foreign_key: rel_author_parent_key,
    target_key: rel_author_target_key,
    assign: rel_author_assign,
};

impl core_db::common::model_api::RuntimeModel for ArticleModel {
    type Row = ArticleRow;
    fn hydrate_records<'db>(db: DbConn<'db>, rows: Vec<Self::Row>, base_url: Option<String>) -> core_db::common::model_api::BoxModelFuture<'db, Vec<Self::Record>> {
        Box::pin(async move { crate::generated::models::article::hydrate_records(db, &rows, base_url.as_deref()).await })
    }
    fn record_pk_i64(record: &Self::Record) -> Option<i64> {
        Some(record.id.clone())
    }
    fn relation_runtimes() -> &'static [&'static dyn core_db::common::model_api::ErasedRelationRuntime<Self>] {
        static RELATIONS: [&'static dyn core_db::common::model_api::ErasedRelationRuntime<ArticleModel>; 1] = [
            &REL_RUNTIME_AUTHOR,
        ];
        &RELATIONS
    }
}

pub struct ArticleTableAdapter {
    db: sqlx::PgPool,
}
impl ArticleTableAdapter {
    fn parse_col(name: &str) -> Option<ArticleDbCol> {
        match name {
            "id" => Some(ArticleDbCol::Id),
            "author_id" => Some(ArticleDbCol::AuthorId),
            "status" => Some(ArticleDbCol::Status),
            "is_system" => Some(ArticleDbCol::IsSystem),
            _ => None,
        }
    }
    fn parse_locale_field_for_profile_cols(column: &str) -> Option<&'static str> {
        match column {
            "display_name" => Some("display_name"),
            _ => None,
        }
    }
    fn parse_locale_field_for_relation(relation: &str, column: &str) -> Option<&'static str> {
        match relation {
            "author__profile" => Self::parse_locale_field_for_profile_cols(column),
            _ => None,
        }
    }
    fn parse_locale_field(name: &str) -> Option<&'static str> {
        match name {
            "title" => Some("title"),
            _ => None,
        }
    }
    fn parse_like_col(name: &str) -> Option<ArticleDbCol> {
        match name {
            _ => None,
        }
    }
    fn parse_bind_for_col(name: &str, raw: &str) -> Option<BindValue> {
        match name {
            "id" => raw.trim().parse::<i64>().ok().map(Into::into),
            "author_id" => raw.trim().parse::<i64>().ok().map(Into::into),
            "status" => Some(Self::parse_bind(raw.trim())),
            "is_system" => Some(Self::parse_bind(raw.trim())),
            _ => None,
        }
    }
    fn parse_bind_for_profile_cols(column: &str, raw: &str) -> Option<BindValue> {
        match column {
            "id" => raw.trim().parse::<i64>().ok().map(Into::into),
            _ => None,
        }
    }
    fn parse_bind_for_user_cols(column: &str, raw: &str) -> Option<BindValue> {
        match column {
            "id" => raw.trim().parse::<i64>().ok().map(Into::into),
            "name" => Some(raw.trim().to_string().into()),
            "profile_id" => raw.trim().parse::<i64>().ok().map(Into::into),
            _ => None,
        }
    }
    fn parse_bind_for_relation(relation: &str, column: &str, raw: &str) -> Option<BindValue> {
        match relation {
            "author__profile" => Self::parse_bind_for_profile_cols(column, raw),
            "author" => Self::parse_bind_for_user_cols(column, raw),
            _ => None,
        }
    }
    fn parse_bind(raw: &str) -> BindValue {
        let trimmed = raw.trim();
        let lower = trimmed.to_ascii_lowercase(); if lower == "true" { return true.into(); } if lower == "false" { return false.into(); }
        if let Ok(v) = trimmed.parse::<i64>() { return v.into(); }
        if let Ok(v) = trimmed.parse::<rust_decimal::Decimal>() { return v.into(); }
        if let Ok(v) = trimmed.parse::<f64>() { return v.into(); }
        if let Ok(v) = uuid::Uuid::parse_str(trimmed) { return v.into(); }
        if let Some(v) = Self::parse_datetime(trimmed, false) { return v.into(); }
        trimmed.to_string().into()
    }
    fn parse_datetime(raw: &str, end_of_day: bool) -> Option<time::OffsetDateTime> {
        let trimmed = raw.trim();
        if let Ok(dt) = time::OffsetDateTime::parse(trimmed, &time::format_description::well_known::Rfc3339) { return Some(dt); }
        if trimmed.len() == 10 {
            let date = time::Date::parse(trimmed, &time::macros::format_description!("[year]-[month]-[day]")).ok()?;
            let t = if end_of_day { time::Time::from_hms(23, 59, 59).ok()? } else { time::Time::MIDNIGHT };
            return Some(date.with_time(t).assume_offset(time::UtcOffset::UTC));
        }
        None
    }
    fn filter_has_for_profile_cols<'db>(column: &str, rq: Query<'db, ProfileModel>, bind: BindValue) -> Query<'db, ProfileModel> {
        match column {
            "id" => rq.where_col(ProfileDbCol::Id, Op::Eq, bind),
            _ => rq,
        }
    }
    fn filter_locale_has_for_profile_cols<'db>(column: &str, rq: Query<'db, ProfileModel>, field: &str, locale: &str, value: String) -> Query<'db, ProfileModel> {
        match column {
            "display_name" => rq.where_exists_raw("EXISTS (SELECT 1 FROM localized l WHERE l.owner_type = ? AND l.owner_id = profiles.id AND l.field = ? AND l.locale = ? AND l.value = ?)".to_string(), vec![localized::PROFILE_OWNER_TYPE.to_string(), field.to_string(), locale.to_string(), value]),
            _ => rq,
        }
    }
    fn filter_locale_has_like_for_profile_cols<'db>(column: &str, rq: Query<'db, ProfileModel>, field: &str, locale: &str, pattern: String) -> Query<'db, ProfileModel> {
        match column {
            "display_name" => rq.where_exists_raw("EXISTS (SELECT 1 FROM localized l WHERE l.owner_type = ? AND l.owner_id = profiles.id AND l.field = ? AND l.locale = ? AND l.value LIKE ?)".to_string(), vec![localized::PROFILE_OWNER_TYPE.to_string(), field.to_string(), locale.to_string(), pattern]),
            _ => rq,
        }
    }
    fn filter_has_for_user_cols<'db>(column: &str, rq: Query<'db, UserModel>, bind: BindValue) -> Query<'db, UserModel> {
        match column {
            "id" => rq.where_col(UserDbCol::Id, Op::Eq, bind),
            "name" => rq.where_col(UserDbCol::Name, Op::Eq, bind),
            "profile_id" => rq.where_col(UserDbCol::ProfileId, Op::Eq, bind),
            _ => rq,
        }
    }
    fn filter_has_like_for_user_cols<'db>(column: &str, rq: Query<'db, UserModel>, pattern: String) -> Query<'db, UserModel> {
        match column {
            "name" => rq.where_col(UserDbCol::Name, Op::Like, pattern),
            _ => rq,
        }
    }
}
impl DataTableColumnResolver for ArticleTableAdapter {
    fn resolve_col_sql(&self, column: &str) -> Option<&'static str> {
        match column {
            "id" => Some("id"),
            "author_id" => Some("author_id"),
            "status" => Some("status"),
            "is_system" => Some("is_system"),
            _ => None,
        }
    }
    fn resolve_like_col_sql(&self, column: &str) -> Option<&'static str> {
        match column {
            _ => None,
        }
    }
    fn parse_bind_for_col(&self, column: &str, raw: &str) -> Option<BindValue> {
        Self::parse_bind_for_col(column, raw)
    }
    fn resolve_locale_field(&self, column: &str) -> Option<&'static str> {
        Self::parse_locale_field(column)
    }
    fn parse_datetime(&self, raw: &str, end_of_day: bool) -> Option<time::OffsetDateTime> {
        Self::parse_datetime(raw, end_of_day)
    }
    fn table_name(&self) -> &'static str { "articles" }
    fn pk_column(&self) -> &'static str { "id" }
    fn locale_owner_type(&self) -> Option<&'static str> { Some(localized::ARTICLE_OWNER_TYPE) }
}
impl GeneratedTableAdapter for ArticleTableAdapter {
    type Query<'db> = Query<'db, ArticleModel>;
    type Row = ArticleRecord;
    fn model_key(&self) -> &'static str { "Article" }
    fn sortable_columns(&self) -> &'static [&'static str] { static SORTABLE_COLUMNS: &[&str] = &["id", "author_id", "status", "is_system"]; SORTABLE_COLUMNS }
    fn timestamp_columns(&self) -> &'static [&'static str] { static TIMESTAMP_COLUMNS: &[&str] = &[]; TIMESTAMP_COLUMNS }
    fn column_descriptors(&self) -> &'static [DataTableColumnDescriptor] {
        static COLUMN_DESCRIPTORS: [DataTableColumnDescriptor; 5] = [
            DataTableColumnDescriptor { name: "id", label: "ID", data_type: "i64", sortable: true, localized: false, filter_ops: &["eq", "gte", "lte"] },
            DataTableColumnDescriptor { name: "author_id", label: "Author ID", data_type: "i64", sortable: true, localized: false, filter_ops: &["eq", "gte", "lte"] },
            DataTableColumnDescriptor { name: "status", label: "Status", data_type: "ArticleStatus", sortable: true, localized: false, filter_ops: &["eq", "gte", "lte"] },
            DataTableColumnDescriptor { name: "is_system", label: "Is System", data_type: "ArticleSystemFlag", sortable: true, localized: false, filter_ops: &["eq", "gte", "lte"] },
            DataTableColumnDescriptor { name: "title", label: "Title", data_type: "String", sortable: false, localized: true, filter_ops: &["locale_eq", "locale_like"] },
        ];
        &COLUMN_DESCRIPTORS
    }
    fn relation_column_descriptors(&self) -> &'static [DataTableRelationColumnDescriptor] {
        static RELATION_COLUMN_DESCRIPTORS: [DataTableRelationColumnDescriptor; 5] = [
            DataTableRelationColumnDescriptor { relation: "author", column: "id", data_type: "i64", filter_ops: &["has_eq"] },
            DataTableRelationColumnDescriptor { relation: "author", column: "name", data_type: "String", filter_ops: &["has_eq", "has_like"] },
            DataTableRelationColumnDescriptor { relation: "author", column: "profile_id", data_type: "i64", filter_ops: &["has_eq"] },
            DataTableRelationColumnDescriptor { relation: "author__profile", column: "id", data_type: "i64", filter_ops: &["has_eq"] },
            DataTableRelationColumnDescriptor { relation: "author__profile", column: "display_name", data_type: "String", filter_ops: &["locale_has_eq", "locale_has_like"] },
        ];
        &RELATION_COLUMN_DESCRIPTORS
    }
    fn filter_patterns(&self) -> &'static [&'static str] {
        static FILTER_PATTERNS: [&str; 14] = [
            "f-<col>",
            "f-like-<col>",
            "f-gte-<col>",
            "f-lte-<col>",
            "f-date-from-<col>",
            "f-date-to-<col>",
            "f-like-any-<col1|col2|...>",
            "f-any-<col1|col2|...>",
            "f-has-<relation>-<col>",
            "f-has-like-<relation>-<col>",
            "f-locale-<col>",
            "f-locale-like-<col>",
            "f-locale-has-<relation>-<col>",
            "f-locale-has-like-<relation>-<col>",
        ];
        &FILTER_PATTERNS
    }
    fn apply_auto_filter<'db>(&self, query: Query<'db, ArticleModel>, filter: &ParsedFilter, value: &str) -> anyhow::Result<Option<Query<'db, ArticleModel>>> where Self: 'db {
        if let Some(state) = core_datatable::apply_standard_filter(query.clone().into_inner(), filter, value, self)? {
            return Ok(Some(Query::from_inner(state)));
        }
        let trimmed = value.trim();
        if trimmed.is_empty() { return Ok(Some(query)); }
        match filter {
            ParsedFilter::Has { relation, column } => {
                match relation.as_str() {
                    "author" => { let Some(bind) = Self::parse_bind_for_user_cols(column.as_str(), trimmed) else { return Ok(None); }; Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| Self::filter_has_for_user_cols(column.as_str(), rq, bind)))) },
                    "author__profile" => { let Some(bind) = Self::parse_bind_for_profile_cols(column.as_str(), trimmed) else { return Ok(None); }; Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| rq.where_has(UserRel::PROFILE, |rq| Self::filter_has_for_profile_cols(column.as_str(), rq, bind))))) },
                    _ => Ok(None),
                }
            }
            ParsedFilter::HasLike { relation, column } => {
                let pattern = format!("%{}%", trimmed);
                match relation.as_str() {
                    "author" => Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| Self::filter_has_like_for_user_cols(column.as_str(), rq, pattern.clone())))),
                    _ => Ok(None),
                }
            }
            ParsedFilter::LocaleHas { relation, column } => {
                let Some(field) = Self::parse_locale_field_for_relation(relation.as_str(), column.as_str()) else { return Ok(None); };
                let locale = core_i18n::current_locale().to_string();
                match relation.as_str() {
                    "author__profile" => Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| rq.where_has(UserRel::PROFILE, |rq| Self::filter_locale_has_for_profile_cols(column.as_str(), rq, &field, &locale, trimmed.to_string()))))),
                    _ => Ok(None),
                }
            }
            ParsedFilter::LocaleHasLike { relation, column } => {
                let Some(field) = Self::parse_locale_field_for_relation(relation.as_str(), column.as_str()) else { return Ok(None); };
                let locale = core_i18n::current_locale().to_string();
                let pattern = format!("%{}%", trimmed);
                match relation.as_str() {
                    "author__profile" => Ok(Some(query.where_has(ArticleRel::AUTHOR, |rq| rq.where_has(UserRel::PROFILE, |rq| Self::filter_locale_has_like_for_profile_cols(column.as_str(), rq, &field, &locale, pattern.clone()))))),
                    _ => Ok(None),
                }
            }
            _ => Ok(None),
        }
    }
    fn apply_sort<'db>(&self, query: Query<'db, ArticleModel>, column: &str, dir: SortDirection) -> anyhow::Result<Query<'db, ArticleModel>> where Self: 'db {
        let dir = match dir { SortDirection::Asc => OrderDir::Asc, SortDirection::Desc => OrderDir::Desc };
        let next = match column {
            "id" => query.order_by(ArticleDbCol::Id, dir),
            "author_id" => query.order_by(ArticleDbCol::AuthorId, dir),
            "status" => query.order_by(ArticleDbCol::Status, dir),
            "is_system" => query.order_by(ArticleDbCol::IsSystem, dir),
            _ => query,
        };
        Ok(next)
    }
    fn apply_cursor<'db>(&self, query: Query<'db, ArticleModel>, column: &str, dir: SortDirection, cursor: &str) -> anyhow::Result<Option<Query<'db, ArticleModel>>> where Self: 'db {
        let Some(col) = Self::parse_col(column) else { return Ok(None); };
        let Some(bind) = Self::parse_bind_for_col(column, cursor) else { return Ok(None); };
        let op = match dir { SortDirection::Asc => Op::Gt, SortDirection::Desc => Op::Lt };
        Ok(Some(query.where_col(col, op, bind)))
    }
    fn cursor_from_row(&self, row: &ArticleRecord, column: &str) -> Option<String> {
        match column {
            "id" => Some(row.id.to_string()),
            "author_id" => Some(row.author_id.to_string()),
            _ => None,
        }
    }
    fn count<'db>(&self, query: Query<'db, ArticleModel>) -> BoxFuture<'db, anyhow::Result<i64>> where Self: 'db {
        let db = self.db.clone(); Box::pin(async move { query.count(&db).await })
    }
    fn fetch_page<'db>(&self, query: Query<'db, ArticleModel>, page: i64, per_page: i64) -> BoxFuture<'db, anyhow::Result<Vec<ArticleRecord>>> where Self: 'db {
        let db = self.db.clone(); Box::pin(async move { Ok(query.paginate(&db, page, per_page).await?.data) })
    }
}
#[derive(Debug, Clone, Copy)]
pub struct ArticleDataTableConfig {
    pub default_sorting_column: &'static str,
    pub default_sorted: SortDirection,
    pub default_export_ignore_columns: &'static [&'static str],
    pub default_timestamp_columns: &'static [&'static str],
    pub default_unsortable: &'static [&'static str],
    pub default_row_per_page: Option<i64>,
}
impl Default for ArticleDataTableConfig {
    fn default() -> Self {
        Self {
            default_sorting_column: "id",
            default_sorted: SortDirection::Desc,
            default_export_ignore_columns: &["actions", "action"],
            default_timestamp_columns: &[],
            default_unsortable: &[],
            default_row_per_page: None,
        }
    }
}
pub trait ArticleDataTableHooks: Send + Sync + 'static {
    fn scope<'db>(&'db self, query: Query<'db, ArticleModel>, _input: &DataTableInput, _ctx: &DataTableContext) -> Query<'db, ArticleModel> { query }
    fn authorize(&self, _input: &DataTableInput, _ctx: &DataTableContext) -> anyhow::Result<bool> { Ok(true) }
    fn filter_query<'db>(&'db self, _query: Query<'db, ArticleModel>, _filter_key: &str, _value: &str, _input: &DataTableInput, _ctx: &DataTableContext) -> anyhow::Result<Option<Query<'db, ArticleModel>>> { Ok(None) }
    fn filters<'db>(&'db self, query: Query<'db, ArticleModel>, _input: &DataTableInput, _ctx: &DataTableContext) -> anyhow::Result<Query<'db, ArticleModel>> { Ok(query) }
    fn map_row(&self, _row: &mut ArticleRecord, _input: &DataTableInput, _ctx: &DataTableContext) -> anyhow::Result<()> { Ok(()) }
    fn default_row_to_record(&self, row: ArticleRecord) -> anyhow::Result<serde_json::Map<String, serde_json::Value>> {
        let mut record = serde_json::Map::new();
        record.insert("id".to_string(), serde_json::Value::String(row.id.to_string()));
        record.insert("author_id".to_string(), serde_json::to_value(row.author_id.clone())?);
        record.insert("status".to_string(), serde_json::to_value(row.status.clone())?);
        record.insert("is_system".to_string(), serde_json::to_value(row.is_system.clone())?);
        record.insert("status_explained".to_string(), serde_json::to_value(row.status_explained.clone())?);
        record.insert("is_system_explained".to_string(), serde_json::to_value(row.is_system_explained.clone())?);
        record.insert("title".to_string(), serde_json::to_value(row.title.clone())?);
        record.insert("title_translations".to_string(), serde_json::to_value(row.title_translations.clone())?);
        record.insert("hero".to_string(), serde_json::to_value(row.hero.clone())?);
        record.insert("hero_url".to_string(), serde_json::to_value(row.hero_url.clone())?);
        record.insert("meta".to_string(), serde_json::to_value(row.meta.clone())?);
        Ok(record)
    }
    fn row_to_record(&self, row: ArticleRecord, _input: &DataTableInput, _ctx: &DataTableContext) -> anyhow::Result<serde_json::Map<String, serde_json::Value>> {
        self.default_row_to_record(row)
    }
    fn summary<'db>(&'db self, _query: Query<'db, ArticleModel>, _input: &DataTableInput, _ctx: &DataTableContext) -> BoxFuture<'db, anyhow::Result<Option<serde_json::Value>>> { Box::pin(async { Ok(None) }) }
}
#[derive(Default)]
pub struct ArticleDefaultDataTableHooks;
impl ArticleDataTableHooks for ArticleDefaultDataTableHooks {}
pub struct ArticleDataTable<H = ArticleDefaultDataTableHooks> where H: ArticleDataTableHooks {
    pub db: sqlx::PgPool,
    pub hooks: H,
    pub config: ArticleDataTableConfig,
    adapter: ArticleTableAdapter,
}
impl ArticleDataTable<ArticleDefaultDataTableHooks> {
    pub fn new(db: sqlx::PgPool) -> Self {
        Self {
            db: db.clone(),
            hooks: ArticleDefaultDataTableHooks,
            config: ArticleDataTableConfig::default(),
            adapter: ArticleTableAdapter { db },
        }
    }
}
impl<H: ArticleDataTableHooks> ArticleDataTable<H> {
    pub fn with_hooks<NH: ArticleDataTableHooks>(self, hooks: NH) -> ArticleDataTable<NH> {
        ArticleDataTable {
            db: self.db.clone(),
            hooks,
            config: self.config,
            adapter: ArticleTableAdapter { db: self.db },
        }
    }
    pub fn with_config(mut self, config: ArticleDataTableConfig) -> Self {
        self.config = config;
        self
    }
}
impl<H: ArticleDataTableHooks> AutoDataTable for ArticleDataTable<H> {
    type Adapter = ArticleTableAdapter;
    fn adapter(&self) -> &Self::Adapter { &self.adapter }
    fn base_query<'db>(&'db self, input: &DataTableInput, ctx: &DataTableContext) -> Query<'db, ArticleModel> {
        self.hooks.scope(ArticleModel::query(), input, ctx)
    }
    fn authorize(&self, input: &DataTableInput, ctx: &DataTableContext) -> anyhow::Result<bool> { self.hooks.authorize(input, ctx) }
    fn filter_query<'db>(&'db self, query: Query<'db, ArticleModel>, filter_key: &str, value: &str, input: &DataTableInput, ctx: &DataTableContext) -> anyhow::Result<Option<Query<'db, ArticleModel>>> { self.hooks.filter_query(query, filter_key, value, input, ctx) }
    fn filters<'db>(&'db self, query: Query<'db, ArticleModel>, input: &DataTableInput, ctx: &DataTableContext) -> anyhow::Result<Query<'db, ArticleModel>> { self.hooks.filters(query, input, ctx) }
    fn map_row(&self, row: &mut ArticleRecord, input: &DataTableInput, ctx: &DataTableContext) -> anyhow::Result<()> { self.hooks.map_row(row, input, ctx) }
    fn row_to_record(&self, row: ArticleRecord, input: &DataTableInput, ctx: &DataTableContext) -> anyhow::Result<serde_json::Map<String, serde_json::Value>> { self.hooks.row_to_record(row, input, ctx) }
    fn summary<'db>(&'db self, query: Query<'db, ArticleModel>, input: &DataTableInput, ctx: &DataTableContext) -> BoxFuture<'db, anyhow::Result<Option<serde_json::Value>>> where Self: 'db { self.hooks.summary(query, input, ctx) }
    fn default_sorting_column(&self) -> &'static str { self.config.default_sorting_column }
    fn default_sorted(&self) -> SortDirection { self.config.default_sorted }
    fn default_export_ignore_columns(&self) -> &'static [&'static str] { self.config.default_export_ignore_columns }
    fn default_timestamp_columns(&self) -> &'static [&'static str] { self.config.default_timestamp_columns }
    fn default_unsortable(&self) -> &'static [&'static str] { self.config.default_unsortable }
    fn default_row_per_page(&self, ctx: &DataTableContext) -> i64 { self.config.default_row_per_page.unwrap_or(ctx.default_per_page) }
}
use core_db::common::active_record::ActiveRecord;
#[async_trait::async_trait]
impl ActiveRecord for ArticleRecord {
    type Id = i64;
    async fn find(db: &sqlx::PgPool, id: Self::Id) -> anyhow::Result<Option<Self>> {
        ArticleModel::find(db, id).await.map_err(|e| e.into())
    }
}
pub struct ArticleModel;
impl ArticleModel {
    pub const TABLE: &'static str = "articles";
    pub const MODEL_KEY: &'static str = "article";
    pub const PK: &'static str = "id";
    pub fn query<'db>() -> Query<'db, ArticleModel> {
        Query::new()
    }
    pub fn query_with_base_url<'db>(base_url: Option<String>) -> Query<'db, ArticleModel> {
        Query::new_with_base_url(base_url)
    }
    pub fn create<'db>() -> Create<'db, ArticleModel> {
        Create::new()
    }
    pub fn create_with_base_url<'db>(base_url: Option<String>) -> Create<'db, ArticleModel> {
        Create::new_with_base_url(base_url)
    }
    pub fn patch<'db>() -> Patch<'db, ArticleModel> {
        Patch::new()
    }
    pub fn patch_with_base_url<'db>(base_url: Option<String>) -> Patch<'db, ArticleModel> {
        Patch::new_with_base_url(base_url)
    }
    pub async fn find<'db>(db: impl Into<DbConn<'db>>, id: i64) -> Result<Option<ArticleRecord>> {
        Query::<ArticleModel>::new().find(db, id).await
    }
    fn _transform_create_value(col: &str, value: BindValue) -> anyhow::Result<BindValue> {
        let _ = col;
        Ok(value)
    }
    fn _transform_patch_value(col: &str, value: BindValue) -> anyhow::Result<BindValue> {
        let _ = col;
        Ok(value)
    }

    async fn convert_delete_to_update<'tx>(db: &DbConn<'tx>, ids: &[i64], overrides: serde_json::Value) -> Result<u64> {
        let map = overrides.as_object()
            .ok_or_else(|| anyhow::anyhow!("observer overrides must be a JSON object"))?;
        let mut set_clauses: Vec<String> = Vec::new();
        let mut binds: Vec<BindValue> = Vec::new();
        let mut idx = 1usize;
        for (key, val) in map {
            match key.as_str() {
                "id" => {
                    let v: i64 = serde_json::from_value(val.clone())?;
                    set_clauses.push(format!("{} = ${}", "id", idx));
                    binds.push(v.into());
                    idx += 1;
                }
                "author_id" => {
                    let v: i64 = serde_json::from_value(val.clone())?;
                    set_clauses.push(format!("{} = ${}", "author_id", idx));
                    binds.push(v.into());
                    idx += 1;
                }
                "status" => {
                    let v: String = serde_json::from_value(val.clone())?;
                    set_clauses.push(format!("{} = ${}", "status", idx));
                    binds.push(v.into());
                    idx += 1;
                }
                "is_system" => {
                    let v: String = serde_json::from_value(val.clone())?;
                    set_clauses.push(format!("{} = ${}", "is_system", idx));
                    binds.push(v.into());
                    idx += 1;
                }
                other => anyhow::bail!("unknown column '{}' in observer delete overrides", other),
            }
        }
        if set_clauses.is_empty() { anyhow::bail!("observer Modify returned empty overrides"); }
        let phs: Vec<String> = ids.iter().enumerate().map(|(i, _)| format!("${}", idx + i)).collect();
        let sql = format!("UPDATE articles SET {} WHERE id IN ({})", set_clauses.join(", "), phs.join(", "));
        let mut q = sqlx::query(&sql);
        for b in &binds { q = bind_query(q, b.clone()); }
        for id in ids { q = q.bind(id); }
        let res = db.execute(q).await?;
        Ok(res.rows_affected())
    }
}

impl ModelDef for ArticleModel {
    type Pk = i64;
    type Record = ArticleRecord;
    type Create = ArticleCreate;
    type Changes = ArticleChanges;
    const TABLE: &'static str = ArticleModel::TABLE;
    const MODEL_KEY: &'static str = ArticleModel::MODEL_KEY;
    const PK_COL: &'static str = "id";
}

impl core_db::common::model_api::QueryModel for ArticleModel {
    const DEFAULT_SELECT: &'static str = "id, author_id, status, is_system";
    const HAS_SOFT_DELETE: bool = false;
    const SOFT_DELETE_COL: &'static str = "";
    const HAS_CREATED_AT: bool = false;
    const HAS_UPDATED_AT: bool = false;
    const PROFILE_QUERIES: bool = true;
    const OBSERVE_HOOKS: bool = true;
}

impl core_db::common::model_api::ChunkModel for ArticleModel {
    fn record_pk(record: &Self::Record) -> Self::Pk {
        record.id.clone()
    }
}

impl core_db::common::model_api::DeleteModel for ArticleModel {
    fn row_pk(row: &Self::Row) -> Self::Pk {
        row.id.clone()
    }
    fn row_pk_text(row: &Self::Row) -> String {
        row.id.to_string()
    }
    fn delete_override_update<'db>(db: DbConn<'db>, ids: Vec<Self::Pk>, overrides: serde_json::Value) -> core_db::common::model_api::BoxModelFuture<'db, u64> {
        Box::pin(async move { ArticleModel::convert_delete_to_update(&db, &ids, overrides).await })
    }
}

impl core_db::common::model_api::CreateModel for ArticleModel {
    const USE_SNOWFLAKE_ID: bool = true;
    fn build_create_input(state: &CreateState<'_>) -> anyhow::Result<Self::Create> {
        let mut input = ArticleCreate::default();
        for assignment in &state.assignments {
            let bind = &assignment.value;
            match assignment.col_sql {
                "id" => {
                    let value = match bind {
            BindValue::I64(value) => value.clone(),
            other => anyhow::bail!("unexpected bind value '{:?}' for type 'i64'", other),
        };
                    input.id = FieldInput::Set(value);
                }
                "author_id" => {
                    let value = match bind {
            BindValue::I64(value) => value.clone(),
            other => anyhow::bail!("unexpected bind value '{:?}' for type 'i64'", other),
        };
                    input.author_id = FieldInput::Set(value);
                }
                "status" => {
                    let value = match bind {
                BindValue::String(value) => ArticleStatus::from_storage(value)
                    .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleStatus'", value))?,
                BindValue::I64(value) => {
                    let raw = value.to_string();
                    ArticleStatus::from_storage(&raw)
                        .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleStatus'", value))?
                }
                other => anyhow::bail!("unexpected bind value '{:?}' for type 'ArticleStatus'", other),
            };
                    input.status = FieldInput::Set(value);
                }
                "is_system" => {
                    let value = match bind {
                BindValue::String(value) => ArticleSystemFlag::from_storage(value)
                    .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleSystemFlag'", value))?,
                BindValue::I64(value) => {
                    let raw = value.to_string();
                    ArticleSystemFlag::from_storage(&raw)
                        .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleSystemFlag'", value))?
                }
                other => anyhow::bail!("unexpected bind value '{:?}' for type 'ArticleSystemFlag'", other),
            };
                    input.is_system = FieldInput::Set(value);
                }
                _ => {}
            }
        }
        Ok(input)
    }
    fn apply_create_overrides(mut state: CreateState<'_>, overrides: serde_json::Value) -> anyhow::Result<CreateState<'_>> {
        let map = overrides.as_object()
            .ok_or_else(|| anyhow::anyhow!("observer overrides must be a JSON object"))?;
        for (key, val) in map {
            match key.as_str() {
                "id" => {
                    let v: i64 = serde_json::from_value(val.clone())?;
                    state = state.set_col("id", v.into());
                }
                "author_id" => {
                    let v: i64 = serde_json::from_value(val.clone())?;
                    state = state.set_col("author_id", v.into());
                }
                "status" => {
                    let v: String = serde_json::from_value(val.clone())?;
                    state = state.set_col("status", v.into());
                }
                "is_system" => {
                    let v: String = serde_json::from_value(val.clone())?;
                    state = state.set_col("is_system", v.into());
                }
                other => anyhow::bail!("unknown column '{}' in observer create overrides", other),
            }
        }
        Ok(state)
    }
    fn created_row_key(row: &<Self as core_db::common::model_api::RuntimeModel>::Row) -> String {
        row.id.to_string()
    }
    fn transform_create_value(col: &str, value: BindValue) -> anyhow::Result<BindValue> {
        Self::_transform_create_value(col, value)
    }
}

impl core_db::common::model_api::FeaturePersistenceModel for ArticleModel {
    fn create_owner_id(row: &<Self as core_db::common::model_api::RuntimeModel>::Row) -> Option<i64> {
        Some(row.id.clone())
    }
    fn patch_owner_id(pk: &Self::Pk) -> Option<i64> {
        Some(pk.clone())
    }
    fn supported_locales() -> &'static [&'static str] {
        localized::SUPPORTED_LOCALES
    }
    fn localized_owner_type() -> Option<&'static str> {
        Some(localized::ARTICLE_OWNER_TYPE)
    }
    fn meta_owner_type() -> Option<&'static str> {
        Some(localized::ARTICLE_OWNER_TYPE)
    }
    fn attachment_owner_type() -> Option<&'static str> {
        Some(localized::ARTICLE_OWNER_TYPE)
    }
    fn upsert_localized_many<'db>(db: DbConn<'db>, ot: &'static str, oid: i64, f: &'static str, v: HashMap<String, String>) -> core_db::common::model_api::BoxModelFuture<'db, ()> { Box::pin(async move { localized::upsert_localized_many(db, ot, oid, f, &v).await }) }
    fn upsert_meta_many<'db>(db: DbConn<'db>, ot: &'static str, oid: i64, v: HashMap<String, serde_json::Value>) -> core_db::common::model_api::BoxModelFuture<'db, ()> { Box::pin(async move { localized::upsert_meta_many(db, ot, oid, &v).await }) }
    fn clear_attachment_field<'db>(db: DbConn<'db>, ot: &'static str, oid: i64, f: &'static str) -> core_db::common::model_api::BoxModelFuture<'db, ()> { Box::pin(async move { localized::clear_attachment_field(db, ot, oid, f).await }) }
    fn replace_single_attachment<'db>(db: DbConn<'db>, ot: &'static str, oid: i64, f: &'static str, v: AttachmentInput) -> core_db::common::model_api::BoxModelFuture<'db, ()> { Box::pin(async move { localized::replace_single_attachment(db, ot, oid, f, &v).await }) }
    fn add_attachments<'db>(db: DbConn<'db>, ot: &'static str, oid: i64, f: &'static str, v: Vec<AttachmentInput>) -> core_db::common::model_api::BoxModelFuture<'db, ()> { Box::pin(async move { localized::add_attachments(db, ot, oid, f, &v).await }) }
    fn delete_attachment_ids<'db>(db: DbConn<'db>, ot: &'static str, oid: i64, f: &'static str, ids: Vec<uuid::Uuid>) -> core_db::common::model_api::BoxModelFuture<'db, ()> { Box::pin(async move { localized::delete_attachment_ids(db, ot, oid, f, &ids).await }) }
}

impl core_db::common::model_api::CreateField<ArticleModel> for ArticleDbCol {
    type Value = BindValue;
    fn set<'db>(field: Self, state: CreateState<'db>, value: BindValue) -> anyhow::Result<CreateState<'db>> {
        let value = <ArticleModel as core_db::common::model_api::CreateModel>::transform_create_value(field.as_sql(), value)?;
        Ok(state.set_col(field.as_sql(), value))
    }
}

impl core_db::common::model_api::CreateConflictField<ArticleModel> for ArticleDbCol {
    fn on_conflict_do_nothing<'db>(state: CreateState<'db>, fields: &[Self]) -> CreateState<'db> {
        let cols: Vec<&'static str> = fields.iter().map(|f| f.as_sql()).collect();
        state.on_conflict_do_nothing(&cols)
    }
    fn on_conflict_update<'db>(state: CreateState<'db>, fields: &[Self]) -> CreateState<'db> {
        let cols: Vec<&'static str> = fields.iter().map(|f| f.as_sql()).collect();
        state.on_conflict_update(&cols)
    }
}

impl core_db::common::model_api::PatchModel for ArticleModel {
    fn build_patch_changes(state: &PatchState<'_>) -> anyhow::Result<Self::Changes> {
        let mut changes = Self::Changes::default();
        for assignment in &state.assignments {
            let bind = &assignment.value;
            let mode = &assignment.mode;
            match assignment.col_sql {
                "id" => {
                    let value = match bind {
            BindValue::I64(value) => value.clone(),
            other => anyhow::bail!("unexpected bind value '{:?}' for type 'i64'", other),
        };
                    changes.id = Some(match mode {
                        SetMode::Assign => FieldChange::Assign(value),
                        SetMode::Increment => FieldChange::Increment(value),
                        SetMode::Decrement => FieldChange::Decrement(value),
                    });
                }
                "author_id" => {
                    let value = match bind {
            BindValue::I64(value) => value.clone(),
            other => anyhow::bail!("unexpected bind value '{:?}' for type 'i64'", other),
        };
                    changes.author_id = Some(match mode {
                        SetMode::Assign => FieldChange::Assign(value),
                        SetMode::Increment => FieldChange::Increment(value),
                        SetMode::Decrement => FieldChange::Decrement(value),
                    });
                }
                "status" => {
                    let value = match bind {
                BindValue::String(value) => ArticleStatus::from_storage(value)
                    .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleStatus'", value))?,
                BindValue::I64(value) => {
                    let raw = value.to_string();
                    ArticleStatus::from_storage(&raw)
                        .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleStatus'", value))?
                }
                other => anyhow::bail!("unexpected bind value '{:?}' for type 'ArticleStatus'", other),
            };
                    changes.status = Some(match mode {
                        SetMode::Assign => FieldChange::Assign(value),
                        SetMode::Increment => FieldChange::Increment(value),
                        SetMode::Decrement => FieldChange::Decrement(value),
                    });
                }
                "is_system" => {
                    let value = match bind {
                BindValue::String(value) => ArticleSystemFlag::from_storage(value)
                    .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleSystemFlag'", value))?,
                BindValue::I64(value) => {
                    let raw = value.to_string();
                    ArticleSystemFlag::from_storage(&raw)
                        .ok_or_else(|| anyhow::anyhow!("invalid enum storage '{}' for type 'ArticleSystemFlag'", value))?
                }
                other => anyhow::bail!("unexpected bind value '{:?}' for type 'ArticleSystemFlag'", other),
            };
                    changes.is_system = Some(match mode {
                        SetMode::Assign => FieldChange::Assign(value),
                        SetMode::Increment => FieldChange::Increment(value),
                        SetMode::Decrement => FieldChange::Decrement(value),
                    });
                }
                _ => {}
            }
        }
        Ok(changes)
    }
    fn apply_patch_overrides<'db>(mut state: PatchState<'db>, overrides: serde_json::Value) -> anyhow::Result<PatchState<'db>> {
        let map = overrides.as_object()
            .ok_or_else(|| anyhow::anyhow!("observer overrides must be a JSON object"))?;
        for (key, val) in map {
            match key.as_str() {
                "id" => {
                    let v: i64 = serde_json::from_value(val.clone())?;
                    state = state.assign_col("id", v.into());
                }
                "author_id" => {
                    let v: i64 = serde_json::from_value(val.clone())?;
                    state = state.assign_col("author_id", v.into());
                }
                "status" => {
                    let v: String = serde_json::from_value(val.clone())?;
                    state = state.assign_col("status", v.into());
                }
                "is_system" => {
                    let v: String = serde_json::from_value(val.clone())?;
                    state = state.assign_col("is_system", v.into());
                }
                other => anyhow::bail!("unknown column '{}' in observer update overrides", other),
            }
        }
        Ok(state)
    }
    fn row_pk(row: &<Self as core_db::common::model_api::RuntimeModel>::Row) -> Self::Pk {
        row.id.clone()
    }
    fn row_pk_text(row: &<Self as core_db::common::model_api::RuntimeModel>::Row) -> String {
        row.id.to_string()
    }
    fn persist_patch_state<'db>(db: DbConn<'db>, target_ids: Vec<Self::Pk>, state: PatchState<'db>) -> core_db::common::model_api::BoxModelFuture<'db, ()> {
        Box::pin(async move {
            if target_ids.is_empty() {
                return Ok(());
            }
            if !state.translations.is_empty() {
                let supported = localized::SUPPORTED_LOCALES;
                if let Some(map) = state.translations.get("title") {
                    let mut filtered = HashMap::new();
                    for (loc, val) in map {
                        if supported.contains(&loc.as_str()) { filtered.insert(loc.clone(), val.clone()); }
                    }
                    if !filtered.is_empty() {
                        for id in &target_ids {
                            localized::upsert_localized_many(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), "title", &filtered).await?;
                        }
                    }
                }
            }
            if !state.meta.is_empty() {
                for id in &target_ids {
                    localized::upsert_meta_many(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), &state.meta).await?;
                }
            }
            for id in &target_ids {
                for field in &state.attachments_clear_single {
                    localized::clear_attachment_field(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), field).await?;
                }
                for (field, att) in &state.attachments_single {
                    localized::replace_single_attachment(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), field, att).await?;
                }
                for (field, list) in &state.attachments_multi {
                    localized::add_attachments(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), field, list).await?;
                }
                for (field, ids) in &state.attachments_delete_multi {
                    localized::delete_attachment_ids(db.clone(), localized::ARTICLE_OWNER_TYPE, id.clone(), field, ids).await?;
                }
            }
            Ok(())
        })
    }
    fn transform_patch_value(col: &str, value: BindValue) -> anyhow::Result<BindValue> {
        Self::_transform_patch_value(col, value)
    }
}

impl core_db::common::model_api::PatchAssignField<ArticleModel> for ArticleDbCol {
    type Value = BindValue;
    fn assign<'db>(field: Self, state: PatchState<'db>, value: BindValue) -> anyhow::Result<PatchState<'db>> {
        let value = <ArticleModel as core_db::common::model_api::PatchModel>::transform_patch_value(field.as_sql(), value)?;
        Ok(state.assign_col(field.as_sql(), value))
    }
}

impl core_db::common::model_api::PatchNumericField<ArticleModel> for ArticleDbCol {
    fn increment<'db>(field: Self, state: PatchState<'db>, value: BindValue) -> anyhow::Result<PatchState<'db>> {
        match field {
            ArticleDbCol::Id => Ok(state.increment_col(field.as_sql(), value)),
            ArticleDbCol::AuthorId => Ok(state.increment_col(field.as_sql(), value)),
            _ => anyhow::bail!("column '{}' does not support increment", field.as_sql()),
        }
    }
    fn decrement<'db>(field: Self, state: PatchState<'db>, value: BindValue) -> anyhow::Result<PatchState<'db>> {
        match field {
            ArticleDbCol::Id => Ok(state.decrement_col(field.as_sql(), value)),
            ArticleDbCol::AuthorId => Ok(state.decrement_col(field.as_sql(), value)),
            _ => anyhow::bail!("column '{}' does not support decrement", field.as_sql()),
        }
    }
}

impl core_db::common::model_api::ColExpr for ArticleDbCol {
    fn col_sql(self) -> &'static str { self.as_sql() }
}

impl core_db::common::model_api::QueryField<ArticleModel> for ArticleDbCol {
    type Value = BindValue;
    fn where_col<'db>(field: Self, state: QueryState<'db>, op: Op, value: BindValue) -> QueryState<'db> {
        state.where_col_str(field.as_sql(), op, value)
    }
    fn or_where_col<'db>(field: Self, state: QueryState<'db>, op: Op, value: BindValue) -> QueryState<'db> {
        state.or_where_col_str(field.as_sql(), op, value)
    }
    fn where_in<'db>(field: Self, state: QueryState<'db>, values: &[BindValue]) -> QueryState<'db> {
        state.where_in_str(field.as_sql(), values)
    }
    fn order_by<'db>(field: Self, state: QueryState<'db>, dir: OrderDir) -> QueryState<'db> {
        state.order_by_str(field.as_sql(), dir)
    }
    fn where_null<'db>(field: Self, state: QueryState<'db>) -> QueryState<'db> {
        state.where_null_str(field.as_sql())
    }
    fn where_not_null<'db>(field: Self, state: QueryState<'db>) -> QueryState<'db> {
        state.where_not_null_str(field.as_sql())
    }
}

impl core_db::common::model_api::IncludeRelation<ArticleModel> for OneRelation<ArticleModel, UserRecord, 0> {
    fn load_spec<'db>(_relation: Self, _base_url: Option<String>) -> core_db::common::model_api::WithRelationSpec {
        core_db::common::model_api::WithRelationSpec { name: "author", kind: "belongs_to", target_table: "users", target_pk: "id", foreign_key: "author_id", local_key: "id", has_soft_delete: false, selects: vec![], filters: vec![], orders: vec![], limit: None, offset: None, with_deleted: false, only_deleted: false, nested: vec![], counts: vec![], aggregates: vec![] }
    }
}

impl core_db::common::model_api::WhereHasRelation<ArticleModel> for OneRelation<ArticleModel, UserRecord, 0> {
    type Target = UserModel;
    fn where_has<'db, F>(_relation: Self, mut state: QueryState<'db>, scope: F) -> QueryState<'db>
    where
        F: FnOnce(Query<'db, Self::Target>) -> Query<'db, Self::Target>,
    {
        let scoped = scope(UserModel::query_with_base_url(state.base_url.clone()));
        let relation_spec = <Self as core_db::common::model_api::IncludeRelation<ArticleModel>>::load_spec(_relation, state.base_url.clone());
        match core_db::common::model_api::relation_exists_from_query_state(relation_spec, scoped.into_inner(), <UserModel as core_db::common::model_api::QueryModel>::DEFAULT_SELECT) {
            Ok(node) => state.push_relation_exists(core_db::common::model_api::ExistenceBoolean::And, node),
            Err(err) => state.defer_error(err.to_string()),
        }
    }
    fn or_where_has<'db, F>(_relation: Self, mut state: QueryState<'db>, scope: F) -> QueryState<'db>
    where
        F: FnOnce(Query<'db, Self::Target>) -> Query<'db, Self::Target>,
    {
        let scoped = scope(UserModel::query_with_base_url(state.base_url.clone()));
        let relation_spec = <Self as core_db::common::model_api::IncludeRelation<ArticleModel>>::load_spec(_relation, state.base_url.clone());
        match core_db::common::model_api::relation_exists_from_query_state(relation_spec, scoped.into_inner(), <UserModel as core_db::common::model_api::QueryModel>::DEFAULT_SELECT) {
            Ok(node) => state.push_relation_exists(core_db::common::model_api::ExistenceBoolean::Or, node),
            Err(err) => state.defer_error(err.to_string()),
        }
    }
}

impl core_db::common::model_api::RecordOneRelation<ArticleModel> for OneRelation<ArticleModel, UserRecord, 0> {
    type Target = UserRecord;
    fn get<'a>(_relation: Self, record: &'a ArticleRecord) -> Option<&'a Self::Target> {
        record.author.as_deref()
    }
}


