// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by build.rs from Rust model sources + configs.toml

pub(crate) mod enums;
pub use enums::*;
pub(crate) mod admin;
pub use admin::{AdminModel, AdminRecord, AdminCreate, AdminChanges, AdminCol, AdminTableAdapter, AdminDataTable, AdminDataTableConfig, AdminDataTableHooks, AdminDefaultDataTableHooks};
pub(crate) mod article;
pub use article::{ArticleModel, ArticleRecord, ArticleCreate, ArticleChanges, ArticleCol, ArticleTableAdapter, ArticleDataTable, ArticleDataTableConfig, ArticleDataTableHooks, ArticleDefaultDataTableHooks, ArticleRel};
pub(crate) mod profile;
pub use profile::{ProfileModel, ProfileRecord, ProfileCreate, ProfileChanges, ProfileCol, ProfileTableAdapter, ProfileDataTable, ProfileDataTableConfig, ProfileDataTableHooks, ProfileDefaultDataTableHooks};
pub(crate) mod user;
pub use user::{UserModel, UserRecord, UserCreate, UserChanges, UserCol, UserTableAdapter, UserDataTable, UserDataTableConfig, UserDataTableHooks, UserDefaultDataTableHooks, UserRel};
pub(crate) mod common;
pub use common::*;
