import { useEffect } from 'react'
import Prism from 'prismjs'

export function Chapter4NotificationsUsage() {
    useEffect(() => {
        Prism.highlightAll()
    }, [])

    return (
        <div className="space-y-10">
            <div className="space-y-4">
                <h1 className="text-4xl font-extrabold text-gray-900">
                    Chapter 4: Notifications Usage Recipe
                </h1>
                <p className="text-xl text-gray-500">
                    Add notification workflows through jobs and channels while keeping delivery concerns isolated.
                </p>
            </div>

            <div className="prose prose-orange max-w-none">
                <h2>Objective</h2>
                <p>
                    Build a notification pipeline with typed payloads, queue delivery, and channel-specific fan-out.
                </p>

                <h2>Scaffold Now (verified)</h2>
                <ul>
                    <li>No notification module is generated by default.</li>
                    <li>
                        You already have worker infrastructure via <code>app/src/internal/jobs/mod.rs</code>.
                    </li>
                    <li>
                        You already have realtime server baseline via <code>app/src/bin/websocket-server.rs</code>.
                    </li>
                </ul>

                <h2>Concept Extension (optional)</h2>
                <ul>
                    <li>
                        Add domain notifications under <code>app/src/internal/notifications/</code>.
                    </li>
                    <li>
                        Queue email/push jobs in workflows and keep API handlers thin.
                    </li>
                    <li>
                        For realtime delivery, publish from worker using <code>core_realtime::RealtimePublisher</code>.
                    </li>
                    <li>
                        Keep payload DTOs in <code>app/src/contracts/api/v1/&lt;portal&gt;/</code> when exposed to clients.
                    </li>
                </ul>

                <h2>Verify</h2>
                <pre className="bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto text-xs">
                    <code className="language-bash">{`cargo check -p app
./bin/worker
./bin/websocket-server
# trigger your notification workflow endpoint and observe worker logs`}</code>
                </pre>
            </div>
        </div>
    )
}
