[BankStatus]
type = "enum"
storage = "i16"
variants = [
  { name = "Enabled", value = 1 },
  { name = "Disabled", value = 2 }
]

[model.bank]
table = "banks"
pk = "id"
pk_type = "i64"
id_strategy = "snowflake"
soft_delete = false
localized = []
fields = [
  "id:i64",
  "country_iso2:string",
  "name:string",
  "code:Option<String>",
  "logo_url:Option<String>",
  "status:BankStatus",
  "sort_order:i32",
  "created_at:datetime",
  "updated_at:datetime"
]
