[CompanyBankAccountStatus]
type = "enum"
storage = "i16"
variants = [
  { name = "Enabled", value = 1 },
  { name = "Disabled", value = 2 }
]

[model.company_bank_account]
table = "company_bank_accounts"
pk = "id"
pk_type = "i64"
id_strategy = "snowflake"
soft_delete = false
localized = []
fields = [
  "id:i64",
  "bank_id:i64",
  "account_name:string",
  "account_number:string",
  "status:CompanyBankAccountStatus",
  "sort_order:i32",
  "created_at:datetime",
  "updated_at:datetime"
]
relations = ["bank:belongs_to:bank:bank_id:id"]
