[model.introducer_change]
table = "introducer_changes"
pk = "id"
pk_type = "i64"
id_strategy = "snowflake"
soft_delete = false
fields = [
  "id:i64",
  "user_id:i64",
  "from_user_id:Option<i64>",
  "to_user_id:i64",
  "admin_id:i64",
  "remark:Option<String>",
  "created_at:datetime",
  "updated_at:datetime"
]
