[WithdrawalMethod]
type = "enum"
storage = "i16"
variants = [
  { name = "Manual", value = 1 }
]

[WithdrawalStatus]
type = "enum"
storage = "i16"
variants = [
  { name = "Pending", value = 1 },
  { name = "Processing", value = 2 },
  { name = "Approved", value = 3 },
  { name = "Rejected", value = 4 }
]

[WithdrawalReviewAction]
type = "enum"
storage = "i16"
variants = [
  { name = "Process", value = 1 },
  { name = "Approve", value = 2 },
  { name = "Reject", value = 3 }
]

[model.withdrawal]
table = "withdrawals"
pk = "id"
pk_type = "i64"
id_strategy = "snowflake"
soft_delete = false
localized = []
fields = [
  "id:i64",
  "owner_type:OwnerType",
  "owner_id:i64",
  "admin_id:Option<i64>",
  "credit_type:CreditType",
  "withdrawal_method:WithdrawalMethod",
  "bank_id:Option<i64>",
  "bank_account_name:Option<String>",
  "bank_account_number:Option<String>",
  "crypto_network_id:Option<i64>",
  "crypto_wallet_address:Option<String>",
  "conversion_rate:Option<rust_decimal::Decimal>",
  "status:WithdrawalStatus",
  "amount:rust_decimal::Decimal",
  "fee:rust_decimal::Decimal",
  "net_amount:rust_decimal::Decimal",
  "related_key:Option<String>",
  "params:Option<serde_json::Value>",
  "remark:Option<String>",
  "admin_remark:Option<String>",
  "reviewed_at:Option<datetime>",
  "created_at:datetime",
  "updated_at:datetime"
]
relations = ["admin:belongs_to:admin:admin_id:id", "bank:belongs_to:bank:bank_id:id", "crypto_network:belongs_to:crypto_network:crypto_network_id:id"]
