// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

export interface ApiResponse<T> {
  data: T;
  message?: string;
}

export type ApiErrorResponse = { message: string, errors?: { [key in string]?: Array<string> }, };
