// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

export type DataTablePaginationMode = "offset" | "cursor";

export type DataTableSortDirection = "asc" | "desc";

export type DataTableQueryRequestBase = { include_meta: boolean, page?: number | null, per_page?: number | null, cursor?: string, pagination_mode?: DataTablePaginationMode, sorting_column?: string, sorting?: DataTableSortDirection, timezone?: string, created_at_from?: string, created_at_to?: string, };

export type DataTableEmailExportRequestBase = { query: DataTableQueryRequestBase, recipients: Array<string>, subject: string | null, export_file_name: string | null, };

export type DataTableFilterFieldType = "text" | "select" | "number" | "date" | "datetime" | "time" | "boolean" | "contact_input";

export type DataTableFilterOptionDto = { label: string, value: string, };

export type DataTableFilterFieldDto = { field: string, filter_key: string, type: DataTableFilterFieldType, label: string, placeholder: string | null, description: string | null, secondary_filter_key: string | null, options: Array<DataTableFilterOptionDto> | null, };

export type DataTableColumnMetaDto = { name: string, label: string, data_type: string, sortable: boolean, localized: boolean, filter_ops: Array<string>, };

export type DataTableRelationColumnMetaDto = { relation: string, column: string, data_type: string, filter_ops: Array<string>, };

export type DataTableDefaultsDto = { sorting_column: string, sorted: string, per_page: number, export_ignore_columns: Array<string>, timestamp_columns: Array<string>, unsortable: Array<string>, };

export type DataTableMetaDto = { model_key: string, defaults: DataTableDefaultsDto, columns: Array<DataTableColumnMetaDto>, relation_columns: Array<DataTableRelationColumnMetaDto>, filter_rows: (DataTableFilterFieldDto | DataTableFilterFieldDto[])[], };

export type DataTableDiagnosticsDto = { duration_ms: number, auto_filters_applied: number, unknown_filters: Array<string>, unknown_filter_mode: string, };

export interface DataTableQueryResponse<T> {
  records: T[];
  per_page: number;
  total_records: number;
  total_pages: number;
  page: number;
  pagination_mode: string;
  has_more?: boolean;
  next_cursor?: string;
  summary?: unknown;
  diagnostics: DataTableDiagnosticsDto;
  meta?: DataTableMetaDto;
}

export type DataTableEmailExportState = "waiting_csv" | "uploading" | "sending" | "completed" | "failed";

export type DataTableEmailExportStatusDto = { state: DataTableEmailExportState, recipients: Array<string>, subject: string | null, link_url: string | null, error: string | null, updated_at_unix: number, sent_at_unix: number | null, };

export type DataTableEmailExportQueuedDto = { job_id: string, csv_state: string, email_state: DataTableEmailExportState, };

export type DataTableExportStatusResponseDto = { job_id: string, model_key: string, csv_state: string, csv_error: string | null, csv_file_name: string | null, csv_content_type: string | null, csv_total_records: number | null, email: DataTableEmailExportStatusDto | null, };
