// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

export type AdminType = "developer" | "superadmin" | "admin";

export const ADMIN_TYPE: Readonly<Record<string, AdminType>> = {
  DEVELOPER: "developer",
  SUPERADMIN: "superadmin",
  ADMIN: "admin",
};

export const ADMIN_TYPES: ReadonlyArray<AdminType> = [
  "developer",
  "superadmin",
  "admin",
];

export type AuthClientType = "web" | "mobile";

export type ContentPageSystemFlag = "0" | "1";

export const CONTENT_PAGE_SYSTEM_FLAG: Readonly<Record<string, ContentPageSystemFlag>> = {
  _0: "0",
  _1: "1",
};

export const CONTENT_PAGE_SYSTEM_FLAGS: ReadonlyArray<ContentPageSystemFlag> = [
  "0",
  "1",
];

export type Permission = "admin.read" | "admin.manage" | "page.read" | "page.manage";

export interface PermissionMeta {
  key: Permission;
  guard: string;
  label: string;
  group: string;
  description: string;
}

export const PERMISSION_META: ReadonlyArray<PermissionMeta> = [
  { key: "admin.read", guard: "admin", label: "Read Admins", group: "admin", description: "View admin profile and datatable records." },
  { key: "admin.manage", guard: "admin", label: "Manage Admins", group: "admin", description: "Create/update/delete admin records and perform management actions." },
  { key: "page.read", guard: "admin", label: "Read Pages", group: "page", description: "View policy pages and page datatable records." },
  { key: "page.manage", guard: "admin", label: "Manage Pages", group: "page", description: "Update and delete non-system pages." },
];

export const PERMISSIONS: ReadonlyArray<Permission> = [
  "admin.read",
  "admin.manage",
  "page.read",
  "page.manage",
];

export const PERMISSION: Readonly<Record<string, Permission>> = {
  ADMIN_READ: "admin.read",
  ADMIN_MANAGE: "admin.manage",
  PAGE_READ: "page.read",
  PAGE_MANAGE: "page.manage",
};

export const PERMISSION_META_BY_KEY: Readonly<Record<Permission, PermissionMeta>> = {
  "admin.read": { key: "admin.read", guard: "admin", label: "Read Admins", group: "admin", description: "View admin profile and datatable records." },
  "admin.manage": { key: "admin.manage", guard: "admin", label: "Manage Admins", group: "admin", description: "Create/update/delete admin records and perform management actions." },
  "page.read": { key: "page.read", guard: "admin", label: "Read Pages", group: "page", description: "View policy pages and page datatable records." },
  "page.manage": { key: "page.manage", guard: "admin", label: "Manage Pages", group: "page", description: "Update and delete non-system pages." },
};
