// Auto-generated by db-gen. Do not edit.

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize, JsonSchema)]
pub struct PermissionMeta {
    pub key: &'static str,
    pub guard: &'static str,
    pub label: &'static str,
    pub group: &'static str,
    pub description: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
pub enum Permission {
{{permission_variants}}
}

impl ts_rs::TS for Permission {
    type WithoutGenerics = Self;

    fn name() -> String { "Permission".to_string() }
    fn inline() -> String { Self::name() }
    fn inline_flattened() -> String { panic!("Permission cannot be flattened") }
    fn decl() -> String { "type Permission = {{ts_union_literal}};".to_string() }
    fn decl_concrete() -> String { Self::decl() }
}

pub const PERMISSION_META: &[PermissionMeta] = &[
{{permission_meta_entries}}
];

impl Permission {
    pub const fn as_str(self) -> &'static str {
{{as_str_body}}
    }

    pub fn from_str(value: &str) -> Option<Self> {
        match value {
{{from_str_arms}}
            _ => None,
        }
    }

    pub const fn all() -> &'static [Self] {
        &[
{{all_variants}}
        ]
    }

    pub const fn guard(self) -> &'static str {
{{guard_body}}
    }

    pub const fn meta(self) -> &'static PermissionMeta {
{{meta_body}}
    }

    pub fn by_guard(guard: &str) -> Vec<Self> {
        Self::all()
            .iter()
            .copied()
            .filter(|permission| permission.guard().eq_ignore_ascii_case(guard))
            .collect()
    }
}

impl std::fmt::Display for Permission {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl AsRef<str> for Permission {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
