[model.sql_profiler_request]
table = "sql_profiler_requests"
pk = "id"
pk_type = "uuid"
id_strategy = "manual"
disable_timestamps = true
audit = false
profile = false
fields = [
  "id:uuid",
  "request_method:String",
  "request_path:String",
  "total_queries:i32",
  "total_duration_ms:f64",
  "created_at:datetime"
]

[model.sql_profiler_query]
table = "sql_profiler_queries"
pk = "id"
id_strategy = "snowflake"
disable_timestamps = true
audit = false
profile = false
fields = [
  "id:i64",
  "request_id:uuid",
  "table_name:String",
  "operation:String",
  "sql:String",
  "binds:String",
  "duration_us:i64",
  "created_at:datetime"
]
