// Auto-generated by db-gen. Do not edit.
use async_trait::async_trait;
use core_db::common::sql::{DbConn, Op};
use core_web::auth::Guard;
use crate::generated::models::{{provider_snake}}::{ {{provider_title}}Model, {{provider_title}}Record };
use crate::generated::models::personal_access_token::{PersonalAccessTokenCol, PersonalAccessTokenModel, PersonalAccessTokenRecord};

/// {{struct_name}} Guard
#[derive(Clone, Copy)]
pub struct {{struct_name}};

#[async_trait]
impl Guard for {{struct_name}} {
    type User = {{provider_title}}Record;

    fn name() -> &'static str {
        "{{guard_name}}"
    }

    fn tokenable_type() -> Option<&'static str> {
        Some("{{provider_name}}")
    }

    async fn fetch_user<'a>(db: DbConn<'a>, id: &str) -> anyhow::Result<Option<Self::User>> {
{{fetch_user_section}}
    }
}

pub async fn list_tokens<'a>(db: DbConn<'a>, subject_id: &str) -> anyhow::Result<Vec<PersonalAccessTokenRecord>> {
    let tokenable_type = <{{struct_name}} as Guard>::tokenable_type().unwrap_or(<{{struct_name}} as Guard>::name());
    let rows = PersonalAccessTokenModel::query(db)
        .where_col(PersonalAccessTokenCol::TOKENABLE_TYPE, Op::Eq, tokenable_type.to_string())
        .where_col(PersonalAccessTokenCol::TOKENABLE_ID, Op::Eq, subject_id.to_string())
        .all()
        .await?;
    Ok(rows)
}

pub async fn revoke_tokens<'a>(db: DbConn<'a>, subject_id: &str) -> anyhow::Result<u64> {
    let tokenable_type = <{{struct_name}} as Guard>::tokenable_type().unwrap_or(<{{struct_name}} as Guard>::name());
    PersonalAccessTokenModel::query(db)
        .where_col(PersonalAccessTokenCol::TOKENABLE_TYPE, Op::Eq, tokenable_type.to_string())
        .where_col(PersonalAccessTokenCol::TOKENABLE_ID, Op::Eq, subject_id.to_string())
        .patch()
        .assign(PersonalAccessTokenCol::REVOKED_AT, Some(time::OffsetDateTime::now_utc()))?
        .save()
        .await
}
