// Auto-generated by db-gen. Do not edit.
use async_trait::async_trait;
use core_db::common::sql::{DbConn, Op};
use core_web::auth::Guard;
use crate::generated::models::{{provider_snake}}::{ {{provider_title}}View, {{provider_title}}Query };
use crate::generated::models::personal_access_token::{PersonalAccessToken, PersonalAccessTokenView};

/// {{struct_name}} Guard
#[derive(Clone, Copy)]
pub struct {{struct_name}};

#[async_trait]
impl Guard for {{struct_name}} {
    type User = {{provider_title}}View;

    fn name() -> &'static str {
        "{{guard_name}}"
    }

    fn tokenable_type() -> Option<&'static str> {
        Some("{{provider_name}}")
    }

    async fn fetch_user<'a>(db: DbConn<'a>, id: &str) -> anyhow::Result<Option<Self::User>> {
{{fetch_user_section}}
    }
}

pub async fn list_tokens<'a>(db: DbConn<'a>, subject_id: &str) -> anyhow::Result<Vec<PersonalAccessTokenView>> {
    let tokenable_type = <{{struct_name}} as Guard>::tokenable_type().unwrap_or(<{{struct_name}} as Guard>::name());
    PersonalAccessToken::new(db, None)
        .query()
        .where_tokenable_type(Op::Eq, tokenable_type.to_string())
        .where_tokenable_id(Op::Eq, subject_id.to_string())
        .get()
        .await
}

pub async fn revoke_tokens<'a>(db: DbConn<'a>, subject_id: &str) -> anyhow::Result<u64> {
    let tokenable_type = <{{struct_name}} as Guard>::tokenable_type().unwrap_or(<{{struct_name}} as Guard>::name());
    PersonalAccessToken::new(db, None)
        .update()
        .where_tokenable_type(Op::Eq, tokenable_type.to_string())
        .where_tokenable_id(Op::Eq, subject_id.to_string())
        .set_revoked_at(Some(time::OffsetDateTime::now_utc()))
        .save()
        .await
}
