// Auto-generated by db-gen. Do not edit.

{{guard_modules}}

use std::collections::BTreeMap;
use core_web::auth::AuthIdentity;
use core_datatable::DataTableActor;

pub async fn authenticate_any_guard(db: &sqlx::PgPool, token: &str) -> Option<AuthIdentity> {
{{authenticate_any_guard_section}}
}

pub async fn datatable_actor_from_token(db: &sqlx::PgPool, token: &str) -> Option<DataTableActor> {
    let identity = authenticate_any_guard(db, token).await?;
    Some(DataTableActor {
        id: Some(identity.subject_id),
        guard: Some(identity.guard),
        roles: vec![],
        permissions: identity.abilities,
        attributes: BTreeMap::new(),
    })
}
